(() => {
'use strict';
const frame=document.getElementById('appFrame'),box=document.getElementById('tests'),summary=document.getElementById('summary');let results=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitFor(fn,timeout=12000){const t=Date.now();while(Date.now()-t<timeout){try{if(fn())return true;}catch(_){}await sleep(70);}return false;}
function add(name,ok,detail=''){results.push(ok);const r=document.createElement('div');r.className=`test ${ok?'pass':'fail'}`;r.innerHTML=`<div class="name">${ok?'✅':'❌'} ${name}</div>${detail?'<div class="detail"></div>':''}`;if(detail)r.querySelector('.detail').textContent=detail;box.appendChild(r);summary.textContent=`${results.filter(Boolean).length} 통과 · ${results.filter(x=>!x).length} 실패`;}
async function ready(){const ok=await waitFor(()=>frame.contentDocument?.getElementById('input')&&frame.contentWindow?.AICleanerApp);if(!ok)throw new Error('앱 로딩 시간 초과');return{w:frame.contentWindow,d:frame.contentDocument};}
async function core(){results=[];box.textContent='';summary.textContent='실행 중…';try{const{w,d}=await ready();const input=d.getElementById('input'),out=d.getElementById('output');add('버전 JSON 부트',/^v6\.8$/.test(d.getElementById('versionBadge').textContent),d.getElementById('versionBadge').textContent);add('상세 진단 기본 접힘',!d.getElementById('detailDiagnostics').open);input.value='결론적으로 테스트합니다. 가격은 19,900원입니다.\u200B\u00A0';w.AICleanerApp.analyzeNow(false);add('기본 분석',out.value.length>0);add('맞춤법 검사 비활성',input.spellcheck===false&&out.spellcheck===false);const iw=d.getElementById('issuesWidget');iw.click();const apply=d.querySelector('[data-apply]');if(apply){apply.click();add('교정 반영',out.value.includes('그래서'));d.getElementById('undoStep').click();add('단계 실행 취소',out.value.includes('결론적으로'));d.getElementById('redoStep').click();add('단계 다시 실행',out.value.includes('그래서'));}else add('교정 반영',false,'반영 버튼 없음');d.getElementById('rewriteWidget').click();const rw=await waitFor(()=>w.AICleanerRewriteStudio&&!d.getElementById('rewritePanel').hidden);add('재작성 스튜디오 lazy load',rw);if(rw){d.getElementById('rewriteGenerate').click();const made=await waitFor(()=>d.getElementById('rewriteDraft').value.length>0);add('새 초안 생성',made);add('Fact Lock 숫자 보존',d.getElementById('rewriteDraft').value.includes('19,900원'),d.getElementById('rewriteFactSummary').textContent);}d.querySelector('[data-resulttab="diff"]').click();add('변경 비교',d.getElementById('diffCount').textContent.length>0,d.getElementById('diffCount').textContent);}catch(e){add('테스트 실행',false,String(e));}}
document.getElementById('runCore')?.addEventListener('click',core);document.getElementById('runNetwork')?.addEventListener('click',()=>alert('이미지 엔진은 AI 이미지 검사에서 파일을 선택할 때 지연 로드됩니다.'));document.getElementById('reloadApp')?.addEventListener('click',()=>frame.src=`../index.html?test=${Date.now()}`);
})();
