(() => {
'use strict';
const frame=document.getElementById('appFrame'),box=document.getElementById('tests'),summary=document.getElementById('summary');let results=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitFor(fn,timeout=10000){const t=Date.now();while(Date.now()-t<timeout){try{if(fn())return true;}catch(_){}await sleep(60);}return false;}
function add(name,ok,detail=''){results.push(ok);const r=document.createElement('div');r.className=`test ${ok?'pass':'fail'}`;r.innerHTML=`<div class="name">${ok?'✅':'❌'} ${name}</div>${detail?`<div class="detail"></div>`:''}`;if(detail)r.querySelector('.detail').textContent=detail;box.appendChild(r);summary.textContent=`${results.filter(Boolean).length} 통과 · ${results.filter(x=>!x).length} 실패`;}
async function ready(){const ok=await waitFor(()=>frame.contentDocument?.getElementById('input')&&frame.contentDocument?.getElementById('analyze'));if(!ok)throw new Error('앱 로딩 시간 초과');return{w:frame.contentWindow,d:frame.contentDocument};}
async function core(){results=[];box.textContent='';summary.textContent='실행 중…';try{const{d}=await ready();const input=d.getElementById('input'),out=d.getElementById('output');input.value='결론적으로 정말 정말 테스트합니다.\u200B\u00A0';d.getElementById('analyze').click();add('기본 분석',out.value.includes('그래서')===false&&out.value.length>0,`결과 ${out.value.length}자`);add('맞춤법 검사 비활성',input.spellcheck===false&&out.spellcheck===false);add('파일 열기 확장',/\.json/.test(d.getElementById('textFileInput').accept)&&/\.yaml/.test(d.getElementById('textFileInput').accept));add('작성 미리보기는 별도 시각 패널',!!d.getElementById('typingPreviewOverlay')&&!!d.getElementById('typingPreviewButton'));const long='이 문장은 문장 검토 기능을 확인하기 위해 충분히 길게 작성했으며 사용자가 문장을 직접 수정하고 수정된 개수만 정확히 반영되는지 확인할 수 있도록 테스트를 구성한 아주 긴 문장입니다.';input.value=long;d.getElementById('analyze').click();const rw=d.getElementById('reviewWidget');add('문장 검토 위젯',!rw.hidden);rw.click();const area=d.querySelector('[data-redit]'),check=d.querySelector('[data-rsel]');if(area&&check){area.value=area.value+' 수정';area.dispatchEvent(new Event('input',{bubbles:true}));check.checked=true;check.dispatchEvent(new Event('change',{bubbles:true}));add('문장 검토 수정 감지',/수정됨 1개/.test(d.getElementById('reviewEditCount').textContent)&&!d.getElementById('v62ApplyReviews').disabled);}else add('문장 검토 수정 감지',false,'검토 카드 없음');d.getElementById('issuesWidget').hidden=false;d.getElementById('issuesWidget').click();const p=d.getElementById('issuesPanel').getBoundingClientRect(),a=input.getBoundingClientRect();add('팝업 기본 위치가 원본 근처',Math.abs(p.left-a.left)<140,`panel ${Math.round(p.left)} / input ${Math.round(a.left)}`);}catch(e){add('테스트 실행',false,String(e));}}
document.getElementById('runCore')?.addEventListener('click',core);document.getElementById('runNetwork')?.addEventListener('click',()=>alert('네트워크/C2PA 검사는 AI 이미지 검사에서 실제 이미지로 확인해 주세요.'));document.getElementById('reloadApp')?.addEventListener('click',()=>frame.src=`../index.html?test=${Date.now()}`);
})();
