import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..'),repo=path.resolve(root,'..');
const files={html:path.join(root,'index.html'),app:path.join(root,'js','app.js'),rewrite:path.join(root,'js','rewrite-studio.js'),image:path.join(root,'js','image-analyzer.js'),css:path.join(root,'css','app.css'),version:path.join(root,'version.json'),regression:path.join(root,'tests','regression.js'),e2e:path.join(root,'tests','e2e.spec.mjs'),previewPs1:path.join(root,'tests','preview.ps1'),previewCmd:path.join(root,'tests','START-PREVIEW.cmd'),package:path.join(repo,'package.json')};
const failures=[],passes=[];const pass=(n,d='')=>passes.push({n,d}),fail=(n,d='')=>failures.push({n,d});
for(const [n,f] of Object.entries(files))fs.existsSync(f)?pass(`required file: ${n}`,path.relative(root,f)):fail(`required file: ${n}`,`missing ${f}`);
if(!failures.length){
 const html=fs.readFileSync(files.html,'utf8'),app=fs.readFileSync(files.app,'utf8'),rewrite=fs.readFileSync(files.rewrite,'utf8'),image=fs.readFileSync(files.image,'utf8'),css=fs.readFileSync(files.css,'utf8'),ver=JSON.parse(fs.readFileSync(files.version,'utf8')),e2e=fs.readFileSync(files.e2e,'utf8'),pkg=JSON.parse(fs.readFileSync(files.package,'utf8'));
 const ids=[...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]),seen=new Set(),dup=[...new Set(ids.filter(id=>seen.has(id)||!seen.add(id)))];dup.length?fail('duplicate HTML ids',dup.join(', ')):pass('duplicate HTML ids',`0 duplicates across ${ids.length} ids`);
 const idSet=new Set(ids),refs=new Set();for(const src of [app,rewrite,image])for(const re of [/(?:\$|q)\(["']#([A-Za-z][\w:-]*)["']\)/g,/getElementById\(["']([A-Za-z][\w:-]*)["']\)/g])for(const m of src.matchAll(re))refs.add(m[1]);const miss=[...refs].filter(x=>!idSet.has(x)).sort();miss.length?fail('JavaScript DOM id references',miss.join(', ')):pass('JavaScript DOM id references',`${refs.size} referenced ids all exist`);
 String(ver.version)===String(pkg.version)&&String(ver.assetVersion)===String(ver.version).replace(/\D/g,'')?pass('version.json source',`${ver.version} / ${ver.assetVersion}`):fail('version.json source',JSON.stringify({ver,pkg:pkg.version}));
 /fetch\(['"]version\.json\?ts=/.test(html)&&/window\.__AI_CLEANER_VERSION__/.test(html)&&/css\/app\.css\?v=/.test(html)&&/js\/app\.js\?v=/.test(html)?pass('version-driven asset boot','version.json drives core CSS/JS'):fail('version-driven asset boot','dynamic boot missing');
 !/loadScript\(['"]js\/image-analyzer\.js/.test(html)&&/ensureImageAnalyzer/.test(app)&&/ensureRewriteStudio/.test(app)?pass('lazy heavy tools','image + rewrite engines load on demand'):fail('lazy heavy tools','eager or missing lazy loader');
 /const APP_VERSION=String\(APP_META\.version/.test(app)&&!/const APP_VERSION=['"]6\.8/.test(app)?pass('no hard-coded app version','APP_VERSION comes from boot metadata'):fail('no hard-coded app version','hard-coded app version found');
 /captureUpdateDraft/.test(app)&&/restoreUpdateDraft/.test(app)&&/sessionStorage/.test(app)?pass('update draft preservation','capture + restore'):fail('update draft preservation','missing');
 /undoHistory/.test(app)&&/redoHistory/.test(app)&&/renderDiff/.test(app)&&/id="undoStep"/.test(html)&&/id="diffPane"/.test(html)?pass('history and diff UI','undo/redo + diff'):fail('history and diff UI','missing');
 /<details class="card detailDiagnostics"/.test(html)&&/id="detailSummary"/.test(html)?pass('progressive diagnostics','details collapsed by default'):fail('progressive diagnostics','missing');
 /extractFactLocks/.test(rewrite)&&/protectFacts/.test(rewrite)&&/validateFacts/.test(rewrite)&&/id="rewriteFactSummary"/.test(html)?pass('Fact Lock rewrite guard','extract + protect + validate'):fail('Fact Lock rewrite guard','missing');
 /data-direct-typing="true"/.test(html)&&/compositionstart/.test(rewrite)&&/compositionend/.test(rewrite)&&/insertFromPaste/.test(rewrite)&&/directTrustedValue/.test(rewrite)?pass('direct typing verifier','IME aware + paste/drop/synthetic insert guarded'):fail('direct typing verifier','missing');
 /EXIF_VERSION\s*=\s*['"]4\.42\.0['"]/.test(image)&&/C2PA_VERSION\s*=\s*['"]0\.13\.4['"]/.test(image)?pass('image dependency pins','ExifReader 4.42.0 + C2PA 0.13.4'):fail('image dependency pins','missing');
 ['0x200C','0x200D','0x2060'].every(t=>app.includes(t))?pass('meaning-sensitive Unicode guard','ZWJ/ZWNJ/WORD JOINER'):fail('meaning-sensitive Unicode guard','missing');
 /trainedAlgorithmicMedia/.test(image)&&/digitalCapture/.test(image)?pass('C2PA source-type distinction','present'):fail('C2PA source-type distinction','missing');
 /@playwright\/test/.test(e2e)&&pkg.devDependencies?.['@playwright/test']==='1.62.1'?pass('Playwright browser pin','1.62.1'):fail('Playwright browser pin','expected 1.62.1');
 /rewriteWidget/.test(e2e)&&/rewriteFactSummary/.test(e2e)&&/undoStep/.test(e2e)&&/data-xpos/.test(e2e)?pass('browser smoke coverage','rewrite + Fact Lock + history + X-ray'):fail('browser smoke coverage','missing');
 /keyboardEvent|dispatchEvent\(new KeyboardEvent|execCommand\(['"]insertText/.test(app+'\n'+rewrite)?fail('no synthetic external typing automation','synthetic input found'):pass('no synthetic external typing automation','direct verifier + internal result typewriter only');
 /v6\.8\.1 precision UI polish/.test(css)&&/grid-template-columns:minmax\(0,1fr\) 92px minmax\(0,1fr\)/.test(css)&&/transform:none!important/.test(css)?pass('precision responsive controls','bridge + mobile text alignment guard'):fail('precision responsive controls','polish guards missing');
 /queueStats/.test(app)&&/targetChars\(\)/.test(rewrite)&&/queueDirectCompare/.test(rewrite)?pass('long-text UI batching','stats + direct verifier batched/cached'):fail('long-text UI batching','performance batching missing');
 /전화번호/.test(rewrite)&&/해시태그/.test(rewrite)&&/시간/.test(rewrite)?pass('Fact Lock coverage','phone + hashtag + time protected'):fail('Fact Lock coverage','extended locks missing');
 /revealAppliedResult/.test(app)&&/closeAllPanels/.test(app)&&/refreshSuggestionBaseline/.test(app)&&/resultApplied/.test(css)?pass('apply focus flow','close panel + refresh suggestions + reveal result'):fail('apply focus flow','missing focus-flow guards');
 /rewritePanel.*toBeHidden|toBeHidden\(\)/.test(e2e)?pass('browser apply-close coverage','rewrite apply closes panel'):fail('browser apply-close coverage','missing');

 /generatedSourceStamp/.test(rewrite)&&/기준 글이 초안을 만든 뒤 바뀌었습니다/.test(rewrite)&&/ai-cleaner:text-changed/.test(app+rewrite)?pass('stale rewrite guard','source changes lock old draft'):fail('stale rewrite guard','missing');
 /SESSION_KEY='ai-cleaner-rewrite-session-v3'/.test(rewrite)&&/saveSession/.test(rewrite)&&/restoreSession/.test(rewrite)?pass('rewrite session recovery','draft + options survive reload'):fail('rewrite session recovery','missing');
 /FACT_LOCK_LIMIT=240/.test(rewrite)&&/모델\/코드/.test(rewrite)&&/uniqueFactToken/.test(rewrite)?pass('Fact Lock integrity','model codes + collision-safe tokens + cap'):fail('Fact Lock integrity','missing');
 /PANEL_SHEET_BREAKPOINT=980/.test(app)&&/clampPanelToViewport/.test(app)&&/@media\(max-width:980px\)[\s\S]*floatPanel/.test(css)?pass('panel viewport cohesion','tablet sheet + viewport clamp'):fail('panel viewport cohesion','missing');
 /MAX_TEXT_FILE_BYTES=20\*1024\*1024/.test(app)?pass('large text import guard','20MB cap'):fail('large text import guard','missing');
 /revealAppliedResult\(`✓ \${done}개 문장을 결과에 반영했습니다/.test(app)?pass('review apply focus flow','review apply reveals result'):fail('review apply focus flow','missing');
 /원본 직접 쓰기/.test(html)&&/insertFromPaste/.test(rewrite)&&/e\.isTrusted/.test(rewrite)&&/directTrustedValue/.test(rewrite)&&/\['paste','drop','copy','cut'\]/.test(rewrite)&&/원본 직접 작성/.test(rewrite)?pass('original direct-write guard','original-only + clipboard/drop/synthetic input blocked + verified typed result apply'):fail('original direct-write guard','missing');
 /setRangeText\(piece/.test(app)&&/commitProgressiveResult/.test(app)&&/splitGraphemesExact/.test(app)&&/out\.value===typingPreview\.source/.test(app)?pass('internal result typewriter','grapheme incremental write + exact verification'):fail('internal result typewriter','missing');
 /setRangeText\(piece/.test(app)&&!/dispatchEvent\(new KeyboardEvent/.test(app)&&!/new KeyboardEvent/.test(app)?pass('typewriter safety boundary','internal textarea insertion only; no synthetic keyboard events'):fail('typewriter safety boundary','unsafe or missing typewriter path');
 /data:image\/(png|jpeg|webp);base64,/i.test(html)?fail('embedded base64 image bloat','found'):pass('embedded base64 image bloat','none');

 /const BASE='http:\/\/127\.0\.0\.1:4173\/ai-cleaner\/'/.test(e2e)&&!/page\.goto\(['"]\/ai-cleaner\//.test(e2e)&&/APP_VERSION=String\(versionData\.version\)/.test(e2e)?pass('browser test version/base cohesion','absolute preview URL + runtime version source'):fail('browser test version/base cohesion','stale version or relative URL in e2e');
 !/add\(cat,reason,m\[0\],after,kind,m\.index,m\.index\+m\[0\]\.length\);\s*add\(cat,reason,m\[0\],after,kind,m\.index,m\.index\+m\[0\]\.length\);/.test(app)?pass('issue rule uniqueness','rule matches are registered once'):fail('issue rule uniqueness','duplicate add detected');
 /clearTextAnalysis/.test(app)&&/resetTextWorkspace/.test(app)&&/if\(!input\.trim\(\)\)\{clearTextAnalysis/.test(app)?pass('empty input state reset','old result/diagnostics cleared'):fail('empty input state reset','missing blank-state reset');
 /typewriterDisabledState/.test(app)&&/clearTimeout\(timer\).*syncOriginalMetadata/.test(app)&&/cleanProfile/.test(app)?pass('typewriter conflict lock','pending analysis + conflicting controls guarded'):fail('typewriter conflict lock','missing conflict guard');
 /MAX_IMAGE_FILE_BYTES=50\*1024\*1024/.test(image)&&/MAX_IMAGE_PIXELS=60_000_000/.test(image)&&/nextObjectUrl/.test(image)?pass('image resource guard','file/pixel cap + safe object URL swap'):fail('image resource guard','missing image resource guard');
 /countOccurrences/.test(rewrite)&&/required=Math\.max/.test(rewrite)?pass('Fact Lock multiplicity','repeated facts require repeated preservation'):fail('Fact Lock multiplicity','count-aware validation missing');
 /id="directTarget" disabled/.test(html)&&!/option value="output"/.test(html.match(/<select id="directTarget"[\s\S]*?<\/select>/)?.[0]||'')?pass('direct write target lock','original-only selector is immutable'):fail('direct write target lock','direct verifier target can drift');
 /\\\\u\(-\?\\d\+\)/.test(app)||/\\\\u\(-\?\\d\+/.test(app)?pass('RTF unicode import','RTF unicode escape conversion present'):fail('RTF unicode import','unicode escape conversion missing');

}
for(const p of passes)console.log(`PASS ${p.n}${p.d?` — ${p.d}`:''}`);for(const f of failures)console.error(`FAIL ${f.n}${f.d?` — ${f.d}`:''}`);console.log(`\nSummary: ${passes.length} passed, ${failures.length} failed`);if(failures.length)process.exit(1);

