import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..'),repo=path.resolve(root,'..');
const files={html:path.join(root,'index.html'),app:path.join(root,'js','app.js'),rewrite:path.join(root,'js','rewrite-studio.js'),image:path.join(root,'js','image-analyzer.js'),css:path.join(root,'css','app.css'),version:path.join(root,'version.json'),regression:path.join(root,'tests','regression.js'),e2e:path.join(root,'tests','e2e.spec.mjs'),moduleCheck:path.join(root,'tests','module-check.mjs'),eventBus:path.join(root,'js','core','event-bus.js'),historyStore:path.join(root,'js','core','history-store.js'),workLock:path.join(root,'js','core','work-lock.js'),textUtils:path.join(root,'js','core','text-utils.js'),stateStore:path.join(root,'js','core','state-store.js'),textEngine:path.join(root,'js','core','text-engine.js'),diffEngine:path.join(root,'js','core','diff-engine.js'),analysisWorkerAdapter:path.join(root,'js','services','analysis-worker-adapter.js'),analysisPerformance:path.join(root,'js','services','analysis-performance-governor.js'),analysisWorker:path.join(root,'js','workers','text-analysis-worker.js'),analysisCoordinator:path.join(root,'js','services','analysis-coordinator.js'),diffView:path.join(root,'js','ui','diff-view.js'),updateManager:path.join(root,'js','services','update-manager.js'),panelManager:path.join(root,'js','ui','panel-manager.js'),fileImport:path.join(root,'js','features','file-import.js'),typewriterEngine:path.join(root,'js','features','typewriter-engine.js'),projectState:path.join(repo,'PROJECT_HANDOFF','PROJECT_STATE.json'),previewPs1:path.join(root,'tests','preview.ps1'),previewCmd:path.join(root,'tests','START-PREVIEW.cmd'),package:path.join(repo,'package.json')};
const failures=[],passes=[];const pass=(n,d='')=>passes.push({n,d}),fail=(n,d='')=>failures.push({n,d});
for(const [n,f] of Object.entries(files))fs.existsSync(f)?pass(`required file: ${n}`,path.relative(root,f)):fail(`required file: ${n}`,`missing ${f}`);
if(!failures.length){
 const html=fs.readFileSync(files.html,'utf8'),app=fs.readFileSync(files.app,'utf8'),rewrite=fs.readFileSync(files.rewrite,'utf8'),image=fs.readFileSync(files.image,'utf8'),css=fs.readFileSync(files.css,'utf8'),eventBus=fs.readFileSync(files.eventBus,'utf8'),historyStore=fs.readFileSync(files.historyStore,'utf8'),workLock=fs.readFileSync(files.workLock,'utf8'),textUtils=fs.readFileSync(files.textUtils,'utf8'),stateStore=fs.readFileSync(files.stateStore,'utf8'),textEngine=fs.readFileSync(files.textEngine,'utf8'),diffEngine=fs.readFileSync(files.diffEngine,'utf8'),analysisWorkerAdapter=fs.readFileSync(files.analysisWorkerAdapter,'utf8'),analysisPerformance=fs.readFileSync(files.analysisPerformance,'utf8'),analysisWorker=fs.readFileSync(files.analysisWorker,'utf8'),analysisCoordinator=fs.readFileSync(files.analysisCoordinator,'utf8'),diffView=fs.readFileSync(files.diffView,'utf8'),updateManager=fs.readFileSync(files.updateManager,'utf8'),panelManager=fs.readFileSync(files.panelManager,'utf8'),fileImport=fs.readFileSync(files.fileImport,'utf8'),typewriterEngine=fs.readFileSync(files.typewriterEngine,'utf8'),projectState=JSON.parse(fs.readFileSync(files.projectState,'utf8')),ver=JSON.parse(fs.readFileSync(files.version,'utf8')),e2e=fs.readFileSync(files.e2e,'utf8'),pkg=JSON.parse(fs.readFileSync(files.package,'utf8'));
 const ids=[...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]),seen=new Set(),dup=[...new Set(ids.filter(id=>seen.has(id)||!seen.add(id)))];dup.length?fail('duplicate HTML ids',dup.join(', ')):pass('duplicate HTML ids',`0 duplicates across ${ids.length} ids`);
 const idSet=new Set(ids),refs=new Set();for(const src of [app,rewrite,image])for(const re of [/(?:\$|q)\(["']#([A-Za-z][\w:-]*)["']\)/g,/getElementById\(["']([A-Za-z][\w:-]*)["']\)/g])for(const m of src.matchAll(re))refs.add(m[1]);const miss=[...refs].filter(x=>!idSet.has(x)).sort();miss.length?fail('JavaScript DOM id references',miss.join(', ')):pass('JavaScript DOM id references',`${refs.size} referenced ids all exist`);
 String(ver.version)===String(pkg.version)&&String(ver.assetVersion)===String(ver.version).replace(/\D/g,'')?pass('version.json source',`${ver.version} / ${ver.assetVersion}`):fail('version.json source',JSON.stringify({ver,pkg:pkg.version}));
 /fetch\(['"]version\.json\?ts=/.test(html)&&/window\.__AI_CLEANER_VERSION__/.test(html)&&/css\/app\.css\?v=/.test(html)&&/js\/app\.js\?v=/.test(html)?pass('version-driven asset boot','version.json drives core CSS/JS'):fail('version-driven asset boot','dynamic boot missing');
 !/loadScript\(['"]js\/image-analyzer\.js/.test(html)&&/ensureImageAnalyzer/.test(app)&&/ensureRewriteStudio/.test(app)?pass('lazy heavy tools','image + rewrite engines load on demand'):fail('lazy heavy tools','eager or missing lazy loader');
 /const APP_VERSION=String\(APP_META\.version/.test(app)&&!/const APP_VERSION=['"]6\.8/.test(app)?pass('no hard-coded app version','APP_VERSION comes from boot metadata'):fail('no hard-coded app version','hard-coded app version found');
 /captureUpdateDraft/.test(app)&&/restoreUpdateDraft/.test(app)&&/sessionStorage/.test(app)?pass('update draft preservation','capture + restore'):fail('update draft preservation','missing');
 /undoHistory/.test(app)&&/redoHistory/.test(app)&&/renderDiff/.test(app)&&/id="undoStep"/.test(html)&&/id="diffPane"/.test(html)?pass('history and diff UI','undo/redo + diff'):fail('history and diff UI','missing');
 /<details class="card detailDiagnostics"/.test(html)&&/id="detailSummary"/.test(html)?pass('progressive diagnostics','details collapsed by default'):fail('progressive diagnostics','missing');
 /extractFactLocks/.test(rewrite)&&/protectFacts/.test(rewrite)&&/validateFacts/.test(rewrite)&&/id="rewriteFactSummary"/.test(html)?pass('Fact Lock rewrite guard','extract + protect + validate'):fail('Fact Lock rewrite guard','missing');
 /data-direct-typing="true"/.test(html)&&/compositionstart/.test(rewrite)&&/compositionend/.test(rewrite)&&/insertFromPaste/.test(rewrite)&&/directTrustedValue/.test(rewrite)?pass('direct typing verifier','IME aware + paste/drop/synthetic insert guarded'):fail('direct typing verifier','missing');
 /EXIF_VERSION\s*=\s*['"]4\.42\.0['"]/.test(image)&&/C2PA_VERSION\s*=\s*['"]0\.13\.4['"]/.test(image)?pass('image dependency pins','ExifReader 4.42.0 + C2PA 0.13.4'):fail('image dependency pins','missing');
 ['0x200C','0x200D','0x2060'].every(t=>(textEngine+'\n'+textUtils).includes(t))?pass('meaning-sensitive Unicode guard','ZWJ/ZWNJ/WORD JOINER policy lives in text modules'):fail('meaning-sensitive Unicode guard','missing');
 /trainedAlgorithmicMedia/.test(image)&&/digitalCapture/.test(image)?pass('C2PA source-type distinction','present'):fail('C2PA source-type distinction','missing');
 /@playwright\/test/.test(e2e)&&pkg.devDependencies?.['@playwright/test']==='1.62.1'?pass('Playwright browser pin','1.62.1'):fail('Playwright browser pin','expected 1.62.1');
 /workerSuccess/.test(e2e)&&/long live analysis runs through worker-safe adapter/.test(e2e)?pass('browser worker coverage','long live analysis verifies Worker/fallback path'):fail('browser worker coverage','worker E2E missing');
 /window\.__AI_CLEANER_APP_READY__=false/.test(html)&&/classList\.add\('app-ready'\)/.test(html)&&/AICleanerApp\.ready=true/.test(html)&&/ai-cleaner:ready/.test(html)?pass('explicit app readiness contract','flag + class + app property + ready event'):fail('explicit app readiness contract','app-ready lifecycle missing');
 /document\.body\.inert=true/.test(html)&&/document\.body\.inert=false/.test(html)&&/aria-busy/.test(html)&&/app-boot-failed/.test(html)?pass('pre-ready interaction lock','inert + aria-busy + boot failure state'):fail('pre-ready interaction lock','pre-ready interaction is not guarded');
 /async function gotoReady\(page\)/.test(e2e)&&/waitForFunction\(\(\)=>window\.__AI_CLEANER_APP_READY__===true/.test(e2e)&&/await page\.goto\(BASE,\{waitUntil:'domcontentloaded'\}\)/.test(e2e)&&!/async function gotoReady\(page\)\{\s*await gotoReady\(page\)/.test(e2e)?pass('browser readiness navigation','E2E waits for app-ready without recursion'):fail('browser readiness navigation','readiness-aware E2E helper missing or invalid');
 /boot readiness blocks interaction until app wiring is complete/.test(e2e)&&/appReady:window\.AICleanerApp\?\.ready===true/.test(e2e)?pass('browser readiness coverage','browser asserts completed app wiring'):fail('browser readiness coverage','app-ready E2E missing');
 /rewriteWidget/.test(e2e)&&/rewriteFactSummary/.test(e2e)&&/undoStep/.test(e2e)&&/visible text/.test(e2e)?pass('browser smoke coverage','rewrite + Fact Lock + history + visible-text typewriter'):fail('browser smoke coverage','missing');
 /keyboardEvent|dispatchEvent\(new KeyboardEvent|execCommand\(['"]insertText/.test(app+'\n'+rewrite)?fail('no synthetic external typing automation','synthetic input found'):pass('no synthetic external typing automation','direct verifier + internal result typewriter only');
 /v6\.8\.1 precision UI polish/.test(css)&&/transform:none!important/.test(css)?pass('precision responsive controls','legacy control alignment guards retained'):fail('precision responsive controls','polish guards missing');
 /queueStats/.test(app)&&/targetChars\(\)/.test(rewrite)&&/queueDirectCompare/.test(rewrite)?pass('long-text UI batching','stats + direct verifier batched/cached'):fail('long-text UI batching','performance batching missing');
 /전화번호/.test(rewrite)&&/해시태그/.test(rewrite)&&/시간/.test(rewrite)?pass('Fact Lock coverage','phone + hashtag + time protected'):fail('Fact Lock coverage','extended locks missing');
 /revealAppliedResult/.test(app)&&/closeAllPanels/.test(app)&&/refreshSuggestionBaseline/.test(app)&&/resultApplied/.test(css)?pass('apply focus flow','close panel + refresh suggestions + reveal result'):fail('apply focus flow','missing focus-flow guards');
 /rewritePanel.*toBeHidden|toBeHidden\(\)/.test(e2e)?pass('browser apply-close coverage','rewrite apply closes panel'):fail('browser apply-close coverage','missing');


 /id="typingPreviewPanel"/.test(html)&&/class="floatPanel typingPreviewPanel"/.test(html)&&!/typingPreviewOverlay" id="typingPreview/.test(html)&&/FLOAT_PANEL_IDS=\['typingPreviewPanel'/.test(app)?pass('standalone typewriter panel','typewriter controls use shared floating panel system'):fail('standalone typewriter panel','result-local overlay still present or panel not registered');
 /0x00AD/.test(textUtils+textEngine)&&/0x061C/.test(textUtils+textEngine)&&/결과 안전 제거 대상 0개/.test(app)?pass('visible-text post-write audit','SHY/ALM safe cleanup + zero-residue result audit'):fail('visible-text post-write audit','safe cleanup/audit missing');

 /generatedSourceStamp/.test(rewrite)&&/기준 글이 초안을 만든 뒤 바뀌었습니다/.test(rewrite)&&/ai-cleaner:text-changed/.test(app+rewrite)?pass('stale rewrite guard','source changes lock old draft'):fail('stale rewrite guard','missing');
 /SESSION_KEY='ai-cleaner-rewrite-session-v3'/.test(rewrite)&&/saveSession/.test(rewrite)&&/restoreSession/.test(rewrite)?pass('rewrite session recovery','draft + options survive reload'):fail('rewrite session recovery','missing');
 /FACT_LOCK_LIMIT=240/.test(rewrite)&&/모델\/코드/.test(rewrite)&&/uniqueFactToken/.test(rewrite)?pass('Fact Lock integrity','model codes + collision-safe tokens + cap'):fail('Fact Lock integrity','missing');
 /PANEL_SHEET_BREAKPOINT=980/.test(app)&&/clampPanelToViewport/.test(app)&&/@media\(max-width:980px\)[\s\S]*floatPanel/.test(css)?pass('panel viewport cohesion','tablet sheet + viewport clamp'):fail('panel viewport cohesion','missing');
 /maxBytes=20\*1024\*1024/.test(fileImport)&&/FILE_TOO_LARGE/.test(fileImport)?pass('large text import guard','20MB cap owned by file-import service'):fail('large text import guard','missing');
 /revealAppliedResult\(`✓ \${done}개 문장을 결과에 반영했습니다/.test(app)?pass('review apply focus flow','review apply reveals result'):fail('review apply focus flow','missing');
 /원본 직접 쓰기/.test(html)&&/insertFromPaste/.test(rewrite)&&/e\.isTrusted/.test(rewrite)&&/directTrustedValue/.test(rewrite)&&/\['paste','drop','copy','cut'\]/.test(rewrite)&&/원본 직접 작성/.test(rewrite)?pass('original direct-write guard','original-only + clipboard/drop/synthetic input blocked + verified typed result apply'):fail('original direct-write guard','missing');
 /append:piece=>\{out\.setRangeText\(piece/.test(app)&&/commitProgressiveResult/.test(app)&&/createTypewriterEngine/.test(typewriterEngine)&&/splitGraphemesExact/.test(textUtils)&&/sanitizeVisibleTypingSource/.test(textUtils)&&/out\.value===source/.test(app)?pass('internal result typewriter','visible-text sanitizer + modular grapheme writer + exact verification'):fail('internal result typewriter','missing');
 /setRangeText\(piece/.test(app)&&!/dispatchEvent\(new KeyboardEvent/.test(app)&&!/new KeyboardEvent/.test(app)?pass('typewriter safety boundary','internal textarea insertion only; no synthetic keyboard events'):fail('typewriter safety boundary','unsafe or missing typewriter path');
 /data:image\/(png|jpeg|webp);base64,/i.test(html)?fail('embedded base64 image bloat','found'):pass('embedded base64 image bloat','none');

 /const BASE='http:\/\/127\.0\.0\.1:4173\/ai-cleaner\/'/.test(e2e)&&!/page\.goto\(['"]\/ai-cleaner\//.test(e2e)&&/APP_VERSION=String\(versionData\.version\)/.test(e2e)?pass('browser test version/base cohesion','absolute preview URL + runtime version source'):fail('browser test version/base cohesion','stale version or relative URL in e2e');
 !/add\(cat,reason,m\[0\],after,kind,m\.index,m\.index\+m\[0\]\.length\);\s*add\(cat,reason,m\[0\],after,kind,m\.index,m\.index\+m\[0\]\.length\);/.test(app)?pass('issue rule uniqueness','rule matches are registered once'):fail('issue rule uniqueness','duplicate add detected');
 /clearTextAnalysis/.test(app)&&/resetTextWorkspace/.test(app)&&/if\(!input\.trim\(\)\)\{clearTextAnalysis/.test(app)?pass('empty input state reset','old result/diagnostics cleared'):fail('empty input state reset','missing blank-state reset');
 /typewriterDisabledState/.test(app)&&/analysisCoordinator\.cancel\(\)/.test(app)&&/inputDirty\|\|state\.original!==rawSource/.test(app)&&/if\(!analyze\(true\)\)return/.test(app)&&/cleanProfile/.test(app)&&/analyze/.test(app)?pass('typewriter conflict lock','pending analysis cancelled + dirty source synchronized before lock'):fail('typewriter conflict lock','missing dirty-source/typewriter guard');
 /MAX_IMAGE_FILE_BYTES=50\*1024\*1024/.test(image)&&/MAX_IMAGE_PIXELS=60_000_000/.test(image)&&/nextObjectUrl/.test(image)?pass('image resource guard','file/pixel cap + safe object URL swap'):fail('image resource guard','missing image resource guard');
 /countOccurrences/.test(rewrite)&&/required=Math\.max/.test(rewrite)?pass('Fact Lock multiplicity','repeated facts require repeated preservation'):fail('Fact Lock multiplicity','count-aware validation missing');
 /id="directTarget" disabled/.test(html)&&!/option value="output"/.test(html.match(/<select id="directTarget"[\s\S]*?<\/select>/)?.[0]||'')?pass('direct write target lock','original-only selector is immutable'):fail('direct write target lock','direct verifier target can drift');
 fileImport.includes('rtfToText')&&fileImport.includes('String.fromCharCode(cp)')&&fileImport.includes("if(/\\.rtf$/i.test(name))")?pass('RTF unicode import','RTF unicode escape conversion owned by file-import service'):fail('RTF unicode import','unicode escape conversion missing');
 /v6\.8\.6 UI \/ layout stabilization/.test(css)&&/grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\)/.test(css)&&/\.bridgeAction\{position:absolute;left:50%;top:52px/.test(css)&&/typingBridgeStatus/.test(html+app)?pass('two-card floating bridge layout','desktop has no reserved bridge column + live bridge status'):fail('two-card floating bridge layout','layout stabilization contract missing');
 /layout bridge floats between two cards/.test(e2e)&&/bridgePosition/.test(e2e)&&/workspaceCenter/.test(e2e)?pass('browser layout regression coverage','desktop floating bridge + tablet inline bridge'):fail('browser layout regression coverage','layout E2E missing');


 const modularBoot=['js/core/event-bus.js','js/core/history-store.js','js/core/work-lock.js','js/core/text-utils.js','js/core/state-store.js','js/core/text-engine.js','js/core/diff-engine.js','js/services/analysis-worker-adapter.js','js/services/analysis-coordinator.js','js/services/update-manager.js','js/ui/panel-manager.js','js/ui/diff-view.js','js/features/file-import.js','js/features/typewriter-engine.js'].every(x=>html.includes(x));
 modularBoot&&html.indexOf('js/core/event-bus.js')<html.indexOf('js/app.js')?pass('modular boot order','core/ui/feature modules load before app'):fail('modular boot order','module load order missing');
 /createHistoryStore/.test(historyStore)&&/historyStore\.record/.test(app)&&!/let historyState=/.test(app)?pass('history store ownership','history state moved out of app.js'):fail('history store ownership','history still coupled to app');
 /createWorkLock/.test(workLock)&&/workLock\.acquire\('typewriter'\)/.test(app)&&/isBlocked:\(\)=>workLock\.isLocked\(\)/.test(app)?pass('work lock ownership','typewriter/update coordination uses shared lock'):fail('work lock ownership','missing shared work lock');
 /createPanelManager/.test(panelManager)&&/panelManager\.open/.test(app)&&/panelManager\.makeDraggable/.test(app)?pass('panel manager ownership','open/close/drag/clamp extracted'):fail('panel manager ownership','panel logic still coupled');
 /createTypewriterEngine/.test(typewriterEngine)&&/typewriterEngine\.start/.test(app)&&/typewriterEngine\.togglePause/.test(app)?pass('typewriter engine ownership','scheduler state extracted from app'):fail('typewriter engine ownership','typewriter scheduler still coupled');
 /createEventBus/.test(eventBus)&&/eventBus\.emit\('text:changed'/.test(app)&&/ai-cleaner:text-changed/.test(app+rewrite)?pass('event bus compatibility bridge','internal bus + DOM compatibility event'):fail('event bus compatibility bridge','event bridge missing');

 /createTextStateStore/.test(stateStore)&&/textStateStore\.replace/.test(app)&&/const state=textStateStore\.state/.test(app)&&!/let state=/.test(app)?pass('state store ownership','stable state object + revision boundary extracted'):fail('state store ownership','state replacement still coupled to app');
 /createTextEngine/.test(textEngine)&&/textEngine\.analyze/.test(app)&&!/function issues\(/.test(app)&&!/function scan\(/.test(app)?pass('text engine ownership','Unicode scan + issue/sentence analysis extracted'):fail('text engine ownership','text analysis still coupled to app');
 /createFileImportService/.test(fileImport)&&/fileImport\.read/.test(app)&&!/function rtfToText\(/.test(app)&&!/function importedText\(/.test(app)?pass('file import ownership','RTF/HTML/XML/binary guards extracted'):fail('file import ownership','file parsing still coupled to app');
 /createUpdateManager/.test(updateManager)&&/updateManager\.restorePending/.test(app)&&/updateManager\.start/.test(app)&&!/setInterval\(checkForAppUpdate/.test(app)?pass('update manager ownership','version polling + draft lifecycle extracted'):fail('update manager ownership','update lifecycle still coupled to app');
 /revision:textStateStore\.revision/.test(app)&&/textStateStore\.touch\(\)/.test(app)?pass('state revision event boundary','text change events carry store revision'):fail('state revision event boundary','missing revision bridge');
 /splitGraphemesExact/.test(textUtils)&&!/function splitGraphemesExact\(/.test(app)?pass('shared text utilities','grapheme logic extracted'):fail('shared text utilities','grapheme helper duplicated');
 !/data-resulttab="xray"/.test(html)&&!/id="xrayPane"/.test(html)?pass('X-ray UI removal','diagnostic tab removed; technical info remains'):fail('X-ray UI removal','legacy X-ray UI still present');
 /sanitizeVisibleTypingSource/.test(textUtils)&&/LEGACY_V6_LAYER_A/.test(textUtils)&&/classifyTextCodePoint/.test(textUtils)&&/preservedSensitive/.test(textUtils)?pass('visible-text sanitizer policy','old-v6 Layer A inventory + safe cleanup + sensitive preservation'):fail('visible-text sanitizer policy','missing');
 /ZERO WIDTH SPACE/.test(textUtils)&&/ZERO WIDTH NON-JOINER/.test(textUtils)&&/NO-BREAK SPACE/.test(textUtils)&&/old-v6-layer-a-safe-1\.2\.2/.test(textUtils)?pass('old-v6 Layer A inventory','named legacy entries absorbed into shared policy'):fail('old-v6 Layer A inventory','legacy inventory missing');
 /textHygieneAudit/.test(app)&&/원본 발견/.test(app)&&/자동 정리/.test(app)&&/의미상 보존/.test(app)&&/결과 잔여/.test(app)?pass('technical hygiene audit counters','original / cleaned / preserved / residue split'):fail('technical hygiene audit counters','audit split missing');
 /getTextHygienePolicy/.test(textUtils)&&/textHygieneAudit:audit/.test(app)?pass('JSON hygiene audit export','policy + audit included in report'):fail('JSON hygiene audit export','missing');
 /자동작성 원본 새로쓰기/.test(html+app)?pass('typewriter menu naming','자동작성 원본 새로쓰기'):fail('typewriter menu naming','missing');
 /@media\(max-width:420px\)[\s\S]*floatWidget>span:not\(\.widgetIcon\)\{display:inline/.test(css)?pass('mobile widget labels visible','names stay visible on narrow phones'):fail('mobile widget labels visible','labels still hidden');
 /createDiffEngine/.test(diffEngine)&&/createDiffView/.test(diffView)&&/diffView\.render/.test(app)&&!/function lineDiff\(/.test(app)&&!/function commonEdgeMarkup\(/.test(app)?pass('diff engine/render boundary','diff calculation + DOM rendering extracted from app'):fail('diff engine/render boundary','diff still coupled to app');
 /createAnalysisCoordinator/.test(analysisCoordinator)&&/queueLiveAnalysis/.test(app)&&/analysisCoordinator\.schedule/.test(app)&&/analysisCoordinator\.runNow/.test(app)?pass('latest-only analysis coordinator','live analysis scheduled through replaceable compute boundary'):fail('latest-only analysis coordinator','analysis scheduling still coupled');
 /analysis:scheduled/.test(app)&&/analysis:completed/.test(app)&&/String\(\$\('#input'\)\.value\)!==String\(input\)/.test(app)?pass('stale analysis result guard','input snapshot + analysis lifecycle events'):fail('stale analysis result guard','missing stale-result protection');
 /js\/core\/diff-engine\.js/.test(html)&&/js\/services\/analysis-coordinator\.js/.test(html)&&/js\/ui\/diff-view\.js/.test(html)?pass('phase 3 boot modules','diff + coordinator + view load before app'):fail('phase 3 boot modules','new modules missing from boot');
 /compareVersions/.test(updateManager)&&/if\(cmp!==1\)return false/.test(updateManager)?pass('update semver downgrade guard','only strictly newer semantic versions reload'):fail('update semver downgrade guard','stale/older version can trigger reload');
 /lazyScripts\.delete\(src\)/.test(app)&&/script\.remove\(\)/.test(app)?pass('lazy tool retry recovery','failed lazy script can be retried without reload'):fail('lazy tool retry recovery','rejected lazy script remains cached');
 /if\(state\.paused\)\{if\(state\.frame\)caf\(state\.frame\);state\.frame=0;\}/.test(typewriterEngine)&&/if\(state\.running&&!state\.paused&&!state\.frame\)/.test(typewriterEngine)?pass('typewriter idle pause','pause cancels rAF loop and resume schedules one frame'):fail('typewriter idle pause','paused typewriter still spins animation frames');
 /if\(!editor\)\{hideContextMenu\(\);return;\}[\s\S]*e\.preventDefault\(\);showContextMenu/.test(app)&&!/addEventListener\('selectstart'/.test(app)&&!/addEventListener\('dragstart'/.test(app)?pass('native page interactions preserved','custom context menu is scoped to text editors'):fail('native page interactions preserved','global context/selection/drag suppression remains');
 /createAnalysisWorkerAdapter/.test(analysisWorkerAdapter)&&/new WorkerCtor\(workerUrl\)/.test(analysisWorkerAdapter)&&/minChars=6000/.test(analysisWorkerAdapter)?pass('worker analysis adapter','long live analysis uses dedicated Worker boundary'):fail('worker analysis adapter','worker adapter missing or threshold changed');
 /fallbackExecutor/.test(analysisWorkerAdapter)&&/instance\.onerror/.test(analysisWorkerAdapter)&&/instance\.onmessageerror/.test(analysisWorkerAdapter)&&/cancelPending/.test(analysisWorkerAdapter)?pass('worker fallback and cancellation','worker error/messageerror falls back and stale work can be cancelled'):fail('worker fallback and cancellation','missing safe fallback/cancel path');
 /jobTimeoutMs=20000/.test(analysisWorkerAdapter)&&/workerTimeouts/.test(analysisWorkerAdapter)&&/timeout-fallback/.test(analysisWorkerAdapter)?pass('worker hang timeout fallback','hung worker jobs terminate and recover on main thread'):fail('worker hang timeout fallback','worker timeout guard missing');
 /failureCooldownMs=15000/.test(analysisWorkerAdapter)&&/cooldownFallbacks/.test(analysisWorkerAdapter)&&/cooldownUntil/.test(analysisWorkerAdapter)?pass('worker failure circuit breaker','repeated worker infrastructure failures enter cooldown'):fail('worker failure circuit breaker','worker cooldown missing');
 /if\(worker!==instance\)return/.test(analysisWorkerAdapter)&&/onmessage=null;instance\.onerror=null;instance\.onmessageerror=null/.test(analysisWorkerAdapter)?pass('stale worker event isolation','terminated worker events cannot mutate replacement worker'):fail('stale worker event isolation','worker event handlers are not instance-scoped');
 /importScripts\('\.\.\/core\/text-utils\.js'\+q,'\.\.\/core\/text-engine\.js'\+q\)/.test(analysisWorker)&&/engine\.analyze/.test(analysisWorker)&&!/document\.|querySelector/.test(analysisWorker)?pass('worker pure analysis kernel','worker reuses DOM-free text core'):fail('worker pure analysis kernel','worker kernel is missing or DOM-coupled');
 /typeof window!==['"]undefined['"]\?window:globalThis/.test(textUtils)&&/typeof window!==['"]undefined['"]\?window:globalThis/.test(textEngine)?pass('worker-safe text core','text utils/engine run in window or worker global'):fail('worker-safe text core','text modules still require window');
 /createAnalysisWorkerAdapter/.test(app)&&/workerUrl:`js\/workers\/text-analysis-worker\.js\?v=\$\{ASSET_VERSION\}`/.test(app)&&/jobTimeoutMs:20000/.test(app)&&/failureCooldownMs:15000/.test(app)&&/syncExecutor:\(text,options\)=>textEngine\.analyze/.test(app)?pass('adaptive analysis wiring','live analysis worker + timeout/cooldown + immediate sync fallback wired'):fail('adaptive analysis wiring','app worker wiring missing');
 /createAnalysisPerformanceGovernor/.test(analysisPerformance)&&/baseDelay/.test(analysisPerformance)&&/noteInput/.test(analysisPerformance)&&/noteCompleted/.test(analysisPerformance)?pass('adaptive analysis performance governor','length + typing burst + recent duration tune live delay'):fail('adaptive analysis performance governor','governor missing or incomplete');
 /id="analyze"[^>]*>지금 다듬기<\/button>/.test(html)&&!/id="analyze"[^>]*hidden/.test(html)?pass('visible manual analysis action','automatic analysis can be disabled without losing a refresh path'):fail('visible manual analysis action','manual analyze action is hidden or missing');
 /id="resultFreshness"/.test(html)&&/function setInputDirty/.test(app)&&/function ensureFreshAnalysis/.test(app)&&/resultStale/.test(css)&&/diff.*disabled|disabled.*diff/.test(app)?pass('dirty-result coherence boundary','stale result is marked and unsafe result actions are guarded'):fail('dirty-result coherence boundary','stale result can remain actionable');
 /analysisFresh/.test(app)&&/outputBasis/.test(app)&&/outputWasCurrent/.test(app)&&/isBlocked:\(\)=>workLock\.isLocked\(\)\|\|analysisCoordinator\.pending/.test(app)?pass('update draft freshness contract','pending analysis blocks update and stale output is not restored over newer input'):fail('update draft freshness contract','update draft can mix input/output revisions');
 /aria-controls="issuesPanel"/.test(html)&&/aria-controls="reviewPanel"/.test(html)&&/function syncPanelAria/.test(app)&&/aria-expanded/.test(app)?pass('panel trigger ARIA cohesion','floating panel triggers mirror open/closed state'):fail('panel trigger ARIA cohesion','panel trigger state can drift');
 /showToast\.hideTimer/.test(app)&&/clearTimeout\(showToast\.hideTimer\)/.test(app)?pass('toast timer isolation','older toast timers cannot hide a newer message'):fail('toast timer isolation','toast hide timers can race');
 /generationSeq/.test(rewrite)&&/setGenerationBusy/.test(rewrite)&&/const alive=\(\)=>token===generationSeq/.test(rewrite)&&/resetSession\(\)\{generationSeq\+\+/.test(rewrite)&&/clearTimeout\(progressHideTimer\)/.test(rewrite)?pass('rewrite generation transaction','stale async draft generation cannot commit after reset/new run'):fail('rewrite generation transaction','rewrite async work lacks transaction guard');
 /function cancelGeneration/.test(rewrite)&&/selected==='output'&&e\.detail\.kind==='original'/.test(rewrite)&&/기준 글이 바뀌어 생성 작업을 취소했습니다/.test(rewrite)?pass('rewrite source dependency invalidation','original edits invalidate current-result drafts and cancel in-flight generation'):fail('rewrite source dependency invalidation','rewrite source dependency can remain stale');
 /const closed=panelManager\.closeTop\(\)/.test(app)&&/closed\.id==='typingPreviewPanel'&&typewriterEngine\.running/.test(app)&&/closed\.id==='rewritePanel'/.test(app)&&/return visible\[0\]/.test(panelManager)?pass('panel close transaction cleanup','Escape closes panel and cancels associated typewriter/rewrite work'):fail('panel close transaction cleanup','panel close can leave background work running');
 /ai-cleaner:text-changed/.test(rewrite)&&/showStaleGuard\(\)/.test(rewrite)&&!/ai-cleaner:text-changed[^\n]*markStaleIfNeeded/.test(rewrite)?pass('rewrite stale-check deferral','typing invalidates draft cheaply; full source hash stays on explicit validation paths'):fail('rewrite stale-check deferral','long-doc source hashing still runs on each text change');
 /innerHeight-topMin-8/.test(panelManager)&&/maxY=Math\.max\(topMin,innerHeight-panel\.offsetHeight-8\)/.test(panelManager)?pass('desktop panel viewport clamp','drag/resize respects reserved top and bottom viewport edge'):fail('desktop panel viewport clamp','desktop panel can escape viewport');
 /reviewVisibleCount/.test(stateStore+app)&&/전체 후보/.test(app)?pass('review summary/render cohesion','worker summary distinguishes total candidates from rendered subset'):fail('review summary/render cohesion','review count can diverge from lazy panel DOM');
 /analysis-performance-governor\.js/.test(html)&&/createAnalysisPerformanceGovernor/.test(app)&&/analysisPerformance\.noteInput/.test(app)&&/analysisPerformance\.noteCompleted/.test(app)?pass('performance governor boot wiring','governor loads before app and drives live scheduling'):fail('performance governor boot wiring','governor is not wired into live analysis');
 /reviewMeta/.test(textEngine)&&/reviewCount:review\.candidateCount/.test(app)&&/renderAll\(\{deferHeavy:true\}\)/.test(app)?pass('worker review summary boundary','review count arrives with analysis before hidden panel DOM rendering'):fail('worker review summary boundary','review metadata still depends on eager panel rendering');
 /if\(!deferHeavy\|\|!\$\('#reviewPanel'\)\.hidden\)buildReviews\(\)/.test(app)&&/if\(id==='reviewPanel'/.test(app)&&/detailDiagnostics'\)\.addEventListener\('toggle'/.test(app)?pass('lazy hidden diagnostics rendering','review/issues/tech and compare defer work until visible'):fail('lazy hidden diagnostics rendering','hidden diagnostics still render eagerly');
 /async function execute/.test(analysisCoordinator)&&/await executor\(text,options\)/.test(analysisCoordinator)&&/syncExecutor/.test(analysisCoordinator)&&/catch\(_\)\{idleId=null;run\(\);\}/.test(analysisCoordinator)?pass('async latest-only coordinator','scheduled analysis accepts worker Promise and survives idle scheduling failure'):fail('async latest-only coordinator','coordinator is not worker-safe');
 /id="resultCard"/.test(html)&&/function navigateTypewriterResult/.test(app)&&/완료 · 결과 보기/.test(app)&&/scrollToResultDestination/.test(app)?pass('typewriter result navigation','completion closes floating panel and lands on the result card'):fail('typewriter result navigation','completion result navigation missing');
 /resultDestinationPulse/.test(css)&&/scroll-margin-top:78px/.test(css)&&/preferredScrollBehavior/.test(app)?pass('mobile result landing clarity','sticky-header offset + destination pulse + reduced-motion aware scroll'):fail('mobile result landing clarity','result landing visual guidance missing');
 /mobile typewriter completion button closes the panel and navigates to the result card/.test(e2e)&&/mobile typewriter completion auto-navigates when the result button is not tapped/.test(e2e)?pass('browser mobile result-navigation coverage','manual completion action + automatic landing are both covered'):fail('browser mobile result-navigation coverage','mobile typewriter navigation E2E missing');
 /height:auto;min-height:68px/.test(css)&&/resultActions\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)\}/.test(css)&&/narrow mobile header and result actions avoid vertical crowding/.test(e2e)?pass('narrow mobile density polish','wrapped sticky header gets real height and result actions remain compact'):fail('narrow mobile density polish','narrow header/result controls can crowd or overlap');
 /analysisWorker\.terminate\(\)/.test(app)?pass('worker lifecycle cleanup','analysis worker terminates on pagehide'):fail('worker lifecycle cleanup','worker is not terminated on pagehide');
 /function suspendPageWork\(\)/.test(app)&&/analysisCoordinator\.cancel\(\)/.test(app)&&/analysisWorker\.terminate\(\)/.test(app)&&/updateManager\.stop\(\)/.test(app)&&/addEventListener\('pagehide',suspendPageWork\)/.test(app)&&/function resumePageWork\(event\)/.test(app)&&/event\?\.persisted/.test(app)&&/updateManager\.start/.test(app)&&/queueLiveAnalysis/.test(app)&&/addEventListener\('pageshow',resumePageWork\)/.test(app)?pass('page lifecycle cleanup','pagehide suspends work and BFCache pageshow restores polling/analysis'):fail('page lifecycle cleanup','pagehide/pageshow lifecycle guard missing');
 String(projectState.version)===String(ver.version)&&String(projectState.current_version)===String(ver.version)&&String(projectState.assetVersion)===String(ver.assetVersion)&&String(projectState.asset_version)===String(ver.assetVersion)?pass('handoff version consistency','PROJECT_STATE matches runtime version'):fail('handoff version consistency',JSON.stringify({projectState:{version:projectState.version,current_version:projectState.current_version,assetVersion:projectState.assetVersion,asset_version:projectState.asset_version},runtime:ver}));
 const mobileChecks=[
  ['mobile compact panel CSS exists',css.includes('1.0.0 mobile compact panels')&&css.includes('46dvh')&&css.includes('mobileExpanded')],
  ['mobile panel size controls exist',html.includes('data-panel-size="issuesPanel"')&&html.includes('data-panel-size="rewritePanel"')&&html.includes('aria-expanded="false"')],
  ['mobile panel expand logic exists',app.includes('setMobilePanelExpanded')&&app.includes("$$('[data-panel-size]')")],
  ['mobile compact mode hides secondary text',css.includes('.floatPanel:not(.mobileExpanded) .floatHead .sub')],
  ['floating dock stays switchable above panels',css.includes('floatingDock{position:fixed')&&css.includes('z-index:520')],
  ['e2e hidden typewriter speed setup',e2e.includes("typingPreviewSpeed').evaluate")&&!e2e.includes("typingPreviewSpeed').selectOption")],
  ['e2e panel switch coverage',e2e.includes("issuesPanel')).toBeHidden")],
  ['e2e completed rewrite transaction wait',e2e.includes("#rewritePanel')).toHaveAttribute('aria-busy','true')")&&e2e.includes("#rewritePanel')).toHaveAttribute('aria-busy','false')")],
  ['e2e in-flight rewrite source cancellation',e2e.includes('rewrite source change cancels an in-flight draft transaction')&&e2e.includes('기준 글이 바뀌어 생성 작업을 취소했습니다.')],
  ['product semver baseline',/^1\.\d+\.\d+$/.test(String(ver.version))&&String(ver.version)===String(pkg.version)]
 ];
 for(const [name,ok] of mobileChecks)ok?pass(name):fail(name);

}
for(const p of passes)console.log(`PASS ${p.n}${p.d?` — ${p.d}`:''}`);for(const f of failures)console.error(`FAIL ${f.n}${f.d?` — ${f.d}`:''}`);
console.log(`\nSummary: ${passes.length} passed, ${failures.length} failed`);if(failures.length)process.exit(1);

