const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const sample='AI가\u200B 쓴 글에는\u200E 보이지 않는 문자가 섞일 수 있어요.\u00A0\n\n결론적으로 이번 제품은 생각보다 사용감이 좋았습니다.\n정말 정말 좋은 제품이라서 적극 추천드립니다.\n\n자주 묻는 질문 (FAQ)';
const specialSpaces=new Set([0xA0,0x1680,0x2000,0x2001,0x2002,0x2003,0x2004,0x2005,0x2006,0x2007,0x2008,0x2009,0x200A,0x202F,0x205F,0x3000]);
const removable=new Set([0x200B,0x200E,0x200F,0x202A,0x202B,0x202C,0x202D,0x202E,0x2066,0x2067,0x2068,0x2069,0xFEFF]);
const sensitive=new Set([0x200C,0x200D,0x2060]);
const lookalike={'а':'Cyrillic a','е':'Cyrillic e','о':'Cyrillic o','р':'Cyrillic er','с':'Cyrillic es','х':'Cyrillic ha','у':'Cyrillic u','і':'Cyrillic i'};
let state={original:'',base:'',working:'',chars:[],allChars:[],issues:[],applied:new Set(),manual:false,homoglyphs:[],reviews:[],score:100};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hex=cp=>'U+'+cp.toString(16).toUpperCase().padStart(4,'0');
function info(ch,pos,profile){const cp=ch.codePointAt(0),code=hex(cp);if(specialSpaces.has(cp))return{pos,code,name:'SPECIAL SPACE',type:'특수 공백',auto:profile==='standard',action:profile==='standard'?'일반 공백':'보존',replace:' '};if(removable.has(cp)||((cp<32&&ch!=='\n'&&ch!=='\t')||cp===127))return{pos,code,name:'INVISIBLE / CONTROL',type:'숨은 문자',auto:profile!=='inspect',action:profile==='inspect'?'보존':'삭제',replace:''};if(sensitive.has(cp)||(cp>=0xFE00&&cp<=0xFE0F)||(cp>=0xE0100&&cp<=0xE01EF)||(cp>=0xE0000&&cp<=0xE007F))return{pos,code,name:'MEANING-SENSITIVE UNICODE',type:'의미 민감 문자',auto:false,action:'보존',replace:ch,risk:'문자 결합·이모지·표현에 영향을 줄 수 있어 기본 보존'};return null}
function scan(text){const profile=$('#cleanProfile').value;let clean='',all=[],auto=[],i=0;for(const ch of text){const x=info(ch,i,profile);if(x){all.push({...x,char:ch});if(x.auto){auto.push({...x,char:ch});clean+=x.replace}else clean+=ch}else clean+=ch;i+=ch.length}return{clean,all,auto}}
function homoglyphs(text){let out=[],i=0;for(const ch of text){if(lookalike[ch])out.push({pos:i,char:ch,code:hex(ch.codePointAt(0)),name:lookalike[ch]});i+=ch.length}return out}
function sentences(text){let out=[],start=0,buf='';for(let i=0;i<text.length;i++){buf+=text[i];if(/[.!?。！？]/.test(text[i])||text[i]==='\n'){const t=buf.trim();if(t.length>=4){const lead=buf.indexOf(t);out.push({start:start+Math.max(0,lead),end:start+Math.max(0,lead)+t.length,text:t})}start=i+1;buf=''}}const t=buf.trim();if(t.length>=4){const lead=buf.indexOf(t);out.push({start:start+Math.max(0,lead),end:start+Math.max(0,lead)+t.length,text:t})}return out}
function issues(text){let out=[],id=0;const add=(cat,reason,before,after=null,kind='read',start=-1,end=-1)=>out.push({id:'i'+(++id),cat,reason,before,after,kind,start,end,applicable:typeof after==='string'});const rules=[[/자주 묻는 질문\s*\(FAQ\)/g,'정형 템플릿','의도한 구성인지 확인하세요.','자주 물어보시더라고요','style'],[/결론적으로|요약하자면|정리하자면|마무리하자면/g,'정형 전환어','문맥상 꼭 필요한 연결어인지 확인하세요.','그래서','style'],[/\*\*([^*\n]+)\*\*/g,'마크다운 **','굵게 표시 기호가 남아 있습니다.',null,'format'],[/^(#{1,6})\s+(.+)$/gm,'마크다운 제목','제목 기호가 남아 있습니다.',null,'format']];for(const [re,cat,reason,repl,kind] of rules){let m;while((m=re.exec(text))){const after=cat==='마크다운 **'?m[1]:cat==='마크다운 제목'?m[2]:repl;add(cat,reason,m[0],after,kind,m.index,m.index+m[0].length)}}for(const m of text.matchAll(/\n{3,}/g))add('연속 빈 줄','빈 줄을 줄이면 읽기 흐름이 좋아집니다.',m[0],'\n\n','read',m.index,m.index+m[0].length);if($('#repeat').checked){const words=text.match(/[가-힣A-Za-z0-9]{2,}/g)||[],f={};words.forEach(w=>f[w]=(f[w]||0)+1);Object.entries(f).filter(([,n])=>n>=6).slice(0,5).forEach(([w,n])=>add('반복 단어',`“${w}”가 ${n}회 반복됩니다.`,`${w} × ${n}`,null,'read'))}return out}
function hygiene(text,all,hom){const md=(text.match(/\*\*|^#{1,6}\s/gm)||[]).length;return Math.max(0,100-Math.min(60,all.length*4)-Math.min(20,hom.length*4)-Math.min(20,md*2))}
function analyze(silent=false){const input=$('#input').value;if(!input.trim()){if(!silent)alert('먼저 글을 붙여넣어 주세요.');return}const sc=scan(input);let base=sc.clean;if($('#norm').checked)base=base.normalize('NFKC');const hom=homoglyphs(base);state={original:input,base,working:base,chars:sc.auto,allChars:sc.all,issues:issues(base),applied:new Set(),manual:false,homoglyphs:hom,reviews:[],score:hygiene(input,sc.all,hom)};$('#output').readOnly=true;$('#editResult').textContent='✎ 직접 수정';renderAll()}
function rebuild(){let text=state.base;for(const x of state.issues.filter(x=>state.applied.has(x.id)&&x.applicable&&x.start>=0).sort((a,b)=>b.start-a.start))text=text.slice(0,x.start)+x.after+text.slice(x.end);if(!state.manual)state.working=text;$('#output').value=state.working}
function renderAll(){rebuild();renderDiag();renderIssues();renderChanges();renderTech();renderXray();renderStats();buildReviews();renderCompare();$('#issueCount').textContent=state.issues.length+'건'}
function renderDiag(){const spaces=state.allChars.filter(x=>x.type==='특수 공백').length;$('#diagHidden').textContent=state.allChars.length-spaces;$('#diagSpace').textContent=spaces;$('#diagLanguage').textContent=state.issues.filter(x=>x.kind==='style').length;$('#diagStyle').textContent=state.issues.filter(x=>x.kind==='style').length;$('#diagFormat').textContent=state.issues.filter(x=>x.kind==='format').length;$('#diagRead').textContent=state.issues.filter(x=>x.kind==='read').length;$('#diagAuto').textContent=state.chars.length;$('#diagStatus').textContent=`기술 항목 ${state.allChars.length} · 자동 처리 ${state.chars.length} · 편집 체크 ${state.issues.length}`}
function renderIssues(){const box=$('#issues');if(!state.issues.length){box.innerHTML='<div class="empty">선택 교정이 필요한 항목이 없습니다. 🦊</div>';return}box.innerHTML=state.issues.map(x=>`<div class="item"><div class="itemtop"><span class="tag ${x.kind==='format'?'blue':''}">${esc(x.cat)}</span><span class="sub">${esc(x.before||'')}</span></div><p>${esc(x.reason)}</p><div class="itemactions">${x.applicable?(state.applied.has(x.id)?`<button class="mini undo" data-undo="${x.id}">↶ 원래대로</button>`:`<button class="mini apply" data-apply="${x.id}">적용</button>`):'<span class="tag blue">확인 항목</span>'}</div></div>`).join('');$$('[data-apply]').forEach(b=>b.onclick=()=>{state.applied.add(b.dataset.apply);state.manual=false;renderAll()});$$('[data-undo]').forEach(b=>b.onclick=()=>{state.applied.delete(b.dataset.undo);state.manual=false;renderAll()})}
function renderChanges(){const rows=[];state.chars.forEach(x=>rows.push(`<div class="item"><span class="tag red">${x.code}</span> <b>${esc(x.type)}</b><p>${esc(x.action)} · ${esc(x.name)}</p></div>`));state.allChars.filter(x=>!x.auto).forEach(x=>rows.push(`<div class="item"><span class="tag blue">보존</span> <b>${x.code} ${esc(x.type)}</b><p>${esc(x.risk||x.name)}</p></div>`));state.homoglyphs.forEach(x=>rows.push(`<div class="item"><span class="tag blue">유사문자</span> <b>${esc(x.char)} ${x.code}</b><p>${esc(x.name)} · 자동 교체하지 않음</p></div>`));if(state.manual)rows.push('<div class="item"><span class="tag blue">직접 수정</span> 사용자 편집 반영</div>');$('#changesList').innerHTML=rows.join('')||'<div class="empty">기술적 변경사항이 없습니다.</div>'}
function renderTech(){$('#removalTable').innerHTML=state.allChars.length?state.allChars.slice(0,500).map(x=>`<tr><td>${x.pos}</td><td><b>${x.code}</b></td><td>${esc(x.type)}</td><td>${esc(x.action)}</td><td>${x.auto?'자동':'보존'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">분석된 특수 문자가 없습니다.</td></tr>'}
function renderXray(){const box=$('#xrayView');if(!state.original){box.innerHTML='<div class="empty">텍스트를 입력하면 숨은 문자의 위치를 눈에 보이게 표시합니다.</div>';return}let html='',i=0;for(const ch of state.original){const x=state.allChars.find(v=>v.pos===i);html+=x?`<span class="${x.auto?(x.type==='특수 공백'?'xrhit xrspace':'xrhit'):'xrhit xrkeep'}" title="${esc(x.name)}">${x.code}</span>`:esc(ch);i+=ch.length}box.innerHTML=html}
function renderStats(){const t=state.original||$('#input').value||'',words=(t.match(/[가-힣A-Za-z0-9]{2,}/g)||[]).length,lines=t?t.split(/\r?\n/).length:0;$('#textStats').innerHTML=`<span class="statpill">문자 <b>${[...t].length}</b></span><span class="statpill">단어 <b>${words}</b></span><span class="statpill">줄 <b>${lines}</b></span>`;$('#cleanScore').textContent=`텍스트 위생 점수 ${state.original?state.score:'--'}`}
function buildReviews(){state.reviews=sentences(state.base||'').map((x,i)=>{let score=0,reasons=[];if(x.text.length>100){score+=2;reasons.push('100자 초과 긴 문장')}else if(x.text.length>72){score++;reasons.push('조금 긴 문장')}const is=issues(x.text);if(is.length){score+=Math.min(2,is.length);reasons.push(...is.slice(0,2).map(v=>v.cat))}return{id:'s'+i,...x,score,reasons:[...new Set(reasons)],edit:x.text,selected:score>=1.5}});const box=$('#v62ReviewList');box.innerHTML=state.reviews.length?state.reviews.map(r=>`<div class="v62review ${r.score>=1.5?'attn':''}"><div class="itemtop"><label class="check"><input type="checkbox" data-rsel="${r.id}" ${r.selected?'checked':''}> 선택</label><span class="tag blue">편집 체크 ${r.score.toFixed(1)}</span><span class="v62small">${r.text.length}자</span></div><div class="src">${esc(r.text)}</div><textarea data-redit="${r.id}">${esc(r.edit)}</textarea><div class="v62reason">${r.reasons.length?'확인: '+esc(r.reasons.join(' · ')):'특별한 편집 신호 없음'}</div></div>`).join(''):'<div class="empty">검토할 문장이 없습니다.</div>';$$('[data-rsel]').forEach(e=>e.onchange=()=>{const r=state.reviews.find(x=>x.id===e.dataset.rsel);if(r)r.selected=e.checked});$$('[data-redit]').forEach(e=>e.oninput=()=>{const r=state.reviews.find(x=>x.id===e.dataset.redit);if(r)r.edit=e.value})}
function renderCompare(){if(!state.original){$('#v62HygBefore').textContent='—';$('#v62HygAfter').textContent='—';return}const before=state.score,sc=scan($('#output').value||state.working),after=hygiene($('#output').value||state.working,sc.all,homoglyphs(sc.clean));$('#v62HygBefore').textContent=before+'/100';$('#v62HygAfter').textContent=after+'/100';$('#v62HygDelta').textContent=`기술 흔적 ${state.allChars.length} → ${sc.all.length}`;$('#v62IssueDelta').textContent=`편집 체크 ${state.issues.length} → ${issues(sc.clean).length}`}
function applyReviews(){let text=$('#output').value||state.working,done=0;for(const r of state.reviews.filter(r=>r.selected&&r.edit!==r.text).sort((a,b)=>b.start-a.start)){const idx=text.lastIndexOf(r.text);if(idx>=0){text=text.slice(0,idx)+r.edit+text.slice(idx+r.text.length);done++}}if(!done)return alert('수정한 문장이 없습니다.');state.working=text;state.manual=true;$('#output').value=text;renderChanges();renderCompare()}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
let timer;$('#input').addEventListener('input',()=>{renderStats();if($('#liveScan').checked){clearTimeout(timer);timer=setTimeout(()=>analyze(true),220)}});$('#analyze').onclick=()=>analyze(false);$('#sample').onclick=()=>{$('#input').value=sample;analyze(true)};$('#reset').onclick=()=>location.reload();['norm','repeat','length','liveScan','cleanProfile'].forEach(id=>$('#'+id).addEventListener('change',()=>{if($('#input').value.trim()&&id!=='liveScan')analyze(true)}));$('#copy').onclick=async()=>{if($('#output').value)await navigator.clipboard.writeText($('#output').value)};$('#downloadTxt').onclick=()=>$('#output').value&&download('cleaned-v6.2.txt',$('#output').value,'text/plain;charset=utf-8');$('#downloadJson').onclick=()=>state.original&&download('ai-clean-report-v6.2.json',JSON.stringify({version:'6.2',profile:$('#cleanProfile').value,hygieneScore:state.score,autoProcessed:state.chars,preserved:state.allChars.filter(x=>!x.auto),homoglyphs:state.homoglyphs,suggestions:state.issues},null,2),'application/json;charset=utf-8');$('#undoAll').onclick=()=>{if(!state.original)return;state.applied.clear();state.manual=false;state.working=state.base;renderAll()};$('#editResult').onclick=()=>{if(!state.original)return;if($('#output').readOnly){$('#output').readOnly=false;$('#output').focus();$('#editResult').textContent='✓ 수정 완료'}else{$('#output').readOnly=true;state.working=$('#output').value;state.manual=true;$('#editResult').textContent='✎ 직접 수정';renderChanges();renderCompare()}};$('#output').addEventListener('input',()=>{if(!$('#output').readOnly){state.working=$('#output').value;state.manual=true;renderCompare()}});$('#v62ApplyReviews').onclick=applyReviews;
$('#textFileInput').addEventListener('change',async e=>{const f=e.target.files&&e.target.files[0];if(!f)return;let s=await f.text();if(/\.html?$/i.test(f.name)){const d=new DOMParser().parseFromString(s,'text/html');s=(d.body&&d.body.innerText)||d.documentElement.textContent||''}$('#input').value=s;analyze(true);e.target.value=''});$$('[data-resulttab]').forEach(t=>t.onclick=()=>{$$('[data-resulttab]').forEach(x=>x.classList.remove('active'));t.classList.add('active');['cleaned','xray','changes','review'].forEach(n=>$('#'+n+'Pane').classList.toggle('hidden',t.dataset.resulttab!==n))});$$('[data-tool]').forEach(b=>b.onclick=()=>{$$('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));$('#textTool').classList.toggle('hidden',b.dataset.tool!=='text');$('#imageTool').classList.toggle('hidden',b.dataset.tool!=='image')});
const dz=$('#dropzone'),fi=$('#imageInput');$('#openImage').onclick=()=>fi.click();dz.onclick=e=>{if(!e.target.closest('#openImage'))fi.click()};fi.onchange=()=>fi.files&&fi.files[0]&&loadImage(fi.files[0]);['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0];if(f)loadImage(f)});
async function loadImage(file){if(!/^image\/(png|jpeg|webp)$/i.test(file.type)&&!/\.(png|jpe?g|webp)$/i.test(file.name)){alert('PNG, JPG, WebP만 지원합니다.');return}$('#imageLoadStatus').textContent='분석 중…';const buf=await file.arrayBuffer(),ascii=new TextDecoder('latin1').decode(new Uint8Array(buf)),low=ascii.toLowerCase(),meta={c2pa:/c2pa|jumbf|content credentials/i.test(ascii),gen:(low.match(/openai|dall[·-]?e|firefly|stable diffusion|comfyui|midjourney|imagen|gemini|flux\.1/g)||[]),prompt:/negative prompt|cfg scale|sampler\s*[:=]|seed\s*[:=]|workflow/i.test(ascii),exif:/exif/i.test(ascii),xmp:/xmpmeta|adobe:ns:meta/i.test(ascii)};const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const c=$('#heatCanvas'),max=800,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,w,h);const data=ctx.getImageData(0,0,w,h).data;let alpha=0;for(let i=3;i<data.length;i+=4)if(data[i]<255)alpha++;const ar=alpha/Math.max(1,w*h),score=Math.min(98,Math.round(5+(meta.c2pa?20:0)+(meta.gen.length?35:0)+(meta.prompt?15:0)+Math.min(15,ar*200)));$('#sourceImage').src=url;$('#imageResults').classList.remove('hidden');$('#imageMeta').textContent=`${img.naturalWidth}×${img.naturalHeight} · ${(file.size/1024/1024).toFixed(2)}MB`;$('#imageScoreNum').textContent=score;$('#imageProgress').style.width=score+'%';$('#sigC2PA').textContent=meta.c2pa?'관련 구조 문자열 발견 · 공식 검증 SDK는 다음 단계':'관련 구조 문자열 없음';$('#sigWatermark').textContent='공급자 전용 비가시 워터마크는 인증하지 않음';$('#sigGenerator').textContent=meta.gen.length?[...new Set(meta.gen)].join(', '):'없음';$('#sigPrompt').textContent=meta.prompt?'관련 키워드 발견':'없음';$('#sigAlpha').textContent=ar?`투명 픽셀 ${(ar*100).toFixed(2)}%`:'없음';$('#sigNoise').textContent='정밀 모듈 이사 예정';$('#sigPeriodic').textContent='정밀 모듈 이사 예정';$('#sigLocal').textContent='간이 분석';$('#sigFile').textContent=`EXIF ${meta.exif?'Y':'N'} · XMP ${meta.xmp?'Y':'N'}`;$('#regionLegend').innerHTML='<span class="sub">정밀 국소 분석은 다음 단계에서 모듈화합니다.</span>';$('#evidenceList').innerHTML=meta.c2pa?'<div class="evidenceRow strong"><b>C2PA 단서</b><br>관련 구조 문자열이 있습니다. 아직 암호학적 검증은 하지 않습니다.</div>':'<div class="evidenceRow ok"><b>명시적 C2PA 단서 없음</b><br>없음이 사람 제작을 뜻하지는 않습니다.</div>';$('#imageLoadStatus').textContent='완료'};img.src=url}
renderStats();renderXray();