(()=>{
'use strict';
if(window.GomFoxReach)return;
const $=s=>document.querySelector(s);
let initialized=false,active=false,currentReport=null,fetchSeq=0,showToast=()=>{};
const MAX_SOURCE_CHARS=750000;
const STOP=new Set('그리고 그러나 하지만 또는 또한 대한 위한 관련 경우 통해 있다 있는 하는 했다 한다 것은 하는데 에서 으로 로부터 보다 가장 정말 너무 이런 저런 그 이 저 것 수 등 및 더 한 두 세 with from this that have has were been into about your you are the and for'.split(/\s+/));
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function setStatus(msg,cls=''){const el=$('#reachFetchStatus');if(!el)return;el.className='reachStatus'+(cls?' '+cls:'');el.textContent=msg;}
function isPrivateHost(host){const h=String(host||'').toLowerCase().replace(/^\[|\]$/g,'');if(h==='localhost'||h.endsWith('.local')||h==='0.0.0.0'||h==='::1')return true;if(/^127\./.test(h)||/^10\./.test(h)||/^169\.254\./.test(h)||/^192\.168\./.test(h))return true;const m=h.match(/^172\.(\d{1,3})\./);if(m&&Number(m[1])>=16&&Number(m[1])<=31)return true;return false;}
function parsePublicUrl(raw){let u;try{u=new URL(String(raw||'').trim());}catch(_){throw new Error('올바른 http/https 주소를 입력해 주세요.');}if(!/^https?:$/.test(u.protocol))throw new Error('http/https 주소만 사용할 수 있습니다.');if(isPrivateHost(u.hostname))throw new Error('localhost·사설 네트워크 주소는 가져올 수 없습니다.');return u;}
async function fetchText(url,{timeout=14000}={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'text/html,text/plain,application/xhtml+xml;q=0.9,*/*;q=0.5'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const text=await r.text();if(!text.trim())throw new Error('빈 응답');return{text,contentType:r.headers.get('content-type')||''};}finally{clearTimeout(timer);}}
function htmlToText(raw){if(!/<(?:html|body|article|main|p|h1|h2|div|section)\b/i.test(raw))return raw.trim();const doc=new DOMParser().parseFromString(raw,'text/html');doc.querySelectorAll('script,style,noscript,template,svg,canvas,nav,footer,form').forEach(x=>x.remove());const main=doc.querySelector('article,main,[role="main"]')||doc.body;return (main?.innerText||main?.textContent||'').replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim();}
async function readUrl(raw){const u=parsePublicUrl(raw),seq=++fetchSeq;const sameOrigin=u.origin===location.origin;
if(sameOrigin){setStatus('같은 사이트의 공개 페이지에 직접 연결 중…');try{const res=await fetchText(u.href,{timeout:9000});if(seq!==fetchSeq)return null;const text=htmlToText(res.text);if(text.length>=80)return{url:u.href,text,via:'direct'};}catch(_){}}
if(seq!==fetchSeq)return null;setStatus('공개 페이지를 읽기 전용 Reader로 가져오는 중…');try{const reader='https://r.jina.ai/'+u.href;const res=await fetchText(reader,{timeout:18000});if(seq!==fetchSeq)return null;const text=String(res.text||'').trim();if(text.length<80)throw new Error('가져온 본문이 너무 짧습니다.');return{url:u.href,text,via:'reader'};}catch(err){if(seq!==fetchSeq)return null;throw new Error(`자동 가져오기에 실패했습니다 (${err?.name==='AbortError'?'시간 초과':err?.message||err}). 원문 직접 붙여넣기를 사용해 주세요.`);}}
function tokenize(text){return (text.normalize('NFKC').toLowerCase().match(/[가-힣]{2,}|[a-z][a-z0-9_-]{2,}|\d{2,}/g)||[]).filter(w=>!STOP.has(w));}
function keywords(text,limit=10){const freq=new Map();for(const w of tokenize(text)){if(/^\d+$/.test(w)&&w.length<4)continue;freq.set(w,(freq.get(w)||0)+1);}return [...freq.entries()].sort((a,b)=>b[1]-a[1]||b[0].length-a[0].length).slice(0,limit).map(([word,count])=>({word,count}));}
function firstMeaningfulLine(text){return text.split(/\n+/).map(x=>x.replace(/^#+\s*/, '').trim()).find(x=>x.length>=8&&x.length<=120)||'';}
function buildReport(text,url=''){const clean=String(text||'').replace(/\r\n?/g,'\n').trim().slice(0,MAX_SOURCE_CHARS);const keys=keywords(clean);const k=keys.map(x=>x.word);const lead=k[0]||'핵심 주제',second=k[1]||'정보',third=k[2]||'정리';const title=firstMeaningfulLine(clean);const queries=[`${lead} ${second} 최신 정보`,`${lead} ${third} 팩트체크`,`${lead} 공식 자료`,`${lead} 실제 사례`,`${lead} 주의사항`];const hooks=[title||`${lead}, 지금 확인해야 할 핵심`,`${lead} 관련 핵심만 빠르게 정리`,`${lead}에서 놓치기 쉬운 ${second} 포인트`,`${lead} 정보, 사실과 의견을 나눠서 보기`];const reuse=[{title:'네이버 블로그',text:`${lead} 중심으로 원문 사실값을 유지하고, 출처·날짜를 별도 확인한 뒤 도입-핵심-주의사항-정리 구조로 편집.`},{title:'숏츠 / 릴스',text:`${lead} 한 문장 훅 → ${second} 핵심 2~3개 → 확인 출처 안내 순서로 30~60초 스크립트화.`},{title:'커뮤니티',text:`${lead} 핵심 요약 3줄 + 확인된 사실/의견 구분 + 원문 링크 형태로 짧게 재구성.`}];return{text:clean,url,chars:clean.length,words:tokenize(clean).length,paras:clean.split(/\n\s*\n/).filter(Boolean).length,keywords:keys,queries,hooks,reuse};}
function render(r){currentReport=r;$('#reachChars').textContent=r.chars.toLocaleString();$('#reachWords').textContent=r.words.toLocaleString();$('#reachParas').textContent=r.paras.toLocaleString();$('#reachResultStatus').textContent='분석 완료';$('#reachKeywords').innerHTML=r.keywords.length?r.keywords.map(k=>`<span>${esc(k.word)} <small>×${k.count}</small></span>`).join(''):'<span class="sub">반복 핵심어를 찾지 못했습니다.</span>';$('#reachQueries').innerHTML=r.queries.map(q=>`<div class="reachItem">${esc(q)}</div>`).join('');$('#reachHooks').innerHTML=r.hooks.map((q,i)=>`<div class="reachItem"><b>${i+1}</b>${esc(q)}</div>`).join('');$('#reachReuse').innerHTML=r.reuse.map(x=>`<div class="reachItem"><b>${esc(x.title)}</b><small>${esc(x.text)}</small></div>`).join('');$('#reachGoogle').disabled=!r.keywords.length;$('#reachCopyAll').disabled=false;$('#reachSaveTxt').disabled=false;}
function reportText(r=currentReport){if(!r)return'';return [`GomFox Reach 2.0`,r.url?`원문 URL: ${r.url}`:'','',`[핵심 키워드]`,r.keywords.map(x=>`${x.word} (${x.count})`).join(', '),'',`[검색어 확장]`,...r.queries.map((x,i)=>`${i+1}. ${x}`),'',`[제목·훅 후보]`,...r.hooks.map((x,i)=>`${i+1}. ${x}`),'',`[콘텐츠 재활용 팩]`,...r.reuse.map(x=>`${x.title}: ${x.text}`),'',`[원문]`,r.text].filter(x=>x!==undefined).join('\n');}
async function copy(text,label='복사'){if(!text)return false;try{await navigator.clipboard.writeText(text);showToast(`${label} 완료`);return true;}catch(_){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();showToast(ok?`${label} 완료`:'복사하지 못했습니다. 직접 선택해 주세요.');return ok;}}
function saveTxt(){const text=reportText();if(!text)return;const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`GomFox-Reach-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);}
function analyze(){const text=$('#reachRaw')?.value||'';if(!text.trim()){setStatus('분석할 원문을 입력해 주세요.','warn');$('#reachRaw')?.focus();return false;}if(text.length>MAX_SOURCE_CHARS)setStatus(`긴 원문이라 앞 ${MAX_SOURCE_CHARS.toLocaleString()}자까지만 분석합니다. 원문 입력창 자체는 변경하지 않습니다.`,'warn');render(buildReport(text,$('#reachUrl')?.value.trim()||''));showToast('GomFox Reach 분석 완료');return true;}
function clearAll(){fetchSeq++;currentReport=null;$('#reachUrl').value='';$('#reachRaw').value='';$('#reachChars').textContent='0';$('#reachWords').textContent='0';$('#reachParas').textContent='0';$('#reachKeywords').innerHTML='<span class="sub">원문을 분석하면 표시됩니다.</span>';$('#reachQueries').innerHTML='<span class="sub">검색 의도에 맞는 확인용 검색어를 만듭니다.</span>';$('#reachHooks').innerHTML='<span class="sub">원문의 핵심어를 바탕으로 후보를 만듭니다.</span>';$('#reachReuse').innerHTML='<span class="sub">네이버 블로그·숏츠/릴스·커뮤니티용 작업 가이드를 준비합니다.</span>';$('#reachGoogle').disabled=true;$('#reachCopyAll').disabled=true;$('#reachSaveTxt').disabled=true;$('#reachResultStatus').textContent='분석 대기';setStatus('주소를 넣으면 직접 연결을 먼저 시도하고, 브라우저 차단 시 읽기 전용 폴백을 사용합니다.');}
function init(opts={}){if(opts.showToast)showToast=opts.showToast;if(initialized)return api;const required=['reachFetch','reachUrl','reachRaw','reachAnalyze','reachCopySource','reachCopyAll','reachSaveTxt','reachClear','reachGoogle'];const missing=required.filter(id=>!document.getElementById(id));if(missing.length)throw new Error('Reach UI 누락: '+missing.join(', '));initialized=true;const badge=$('#reachEngineBadge');if(badge)badge.textContent='엔진 연결 완료';$('#reachFetch').addEventListener('click',async()=>{const btn=$('#reachFetch');btn.disabled=true;try{const result=await readUrl($('#reachUrl').value);if(!result)return;$('#reachRaw').value=result.text;$('#reachSourceStatus').textContent=result.via==='direct'?'URL 직접 수집':'URL 폴백 수집';setStatus(result.via==='direct'?'URL 원문을 가져왔습니다.':'브라우저 직접 연결이 제한되어 읽기 전용 폴백으로 원문을 가져왔습니다.','ok');analyze();}catch(err){setStatus(err.message||String(err),'bad');}finally{btn.disabled=false;}});$('#reachAnalyze').addEventListener('click',analyze);$('#reachCopySource').addEventListener('click',()=>copy($('#reachRaw').value,'원문 복사'));$('#reachCopyAll').addEventListener('click',()=>copy(reportText(),'Reach 결과 복사'));$('#reachSaveTxt').addEventListener('click',saveTxt);$('#reachClear').addEventListener('click',clearAll);$('#reachGoogle').addEventListener('click',()=>{const q=currentReport?.queries?.[0]||currentReport?.keywords?.map(x=>x.word).slice(0,3).join(' ');if(!q)return;window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank','noopener,noreferrer');});$('#reachUrl').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#reachFetch').click();}});return api;}
function activate(){active=true;}
function deactivate(){active=false;fetchSeq++;const btn=$('#reachFetch');if(btn)btn.disabled=false;}
const api={init,activate,deactivate,analyze,readUrl,buildReport,get active(){return active;}};window.GomFoxReach=api;
})();
