(()=>{
'use strict';
if(window.GomFoxReach)return;
const $=s=>document.querySelector(s);
let initialized=false,active=false,showToast=()=>{},fetchSeq=0,sourceSeq=0,currentReport=null;
const sources=[];
const MAX_SOURCES=6,MAX_SOURCE_CHARS=500000,MAX_CLAIMS_PER_SOURCE=18;
const STOP=new Set('그리고 그러나 하지만 또는 또한 대한 위한 관련 경우 통해 있다 있는 하는 했다 한다 것은 하는데 에서 으로 로부터 보다 가장 정말 너무 이런 저런 그 이 저 것 수 등 및 더 한 두 세 with from this that have has were been into about your you are the and for'.split(/\s+/));
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function setText(id,v){const el=$('#'+id);if(el)el.textContent=v;}
function setStatus(id,msg,cls=''){const el=$('#'+id);if(!el)return;el.className='reachStatus'+(cls?' '+cls:'');el.textContent=msg;}
function isPrivateHost(host){const h=String(host||'').toLowerCase().replace(/^\[|\]$/g,'');if(h==='localhost'||h.endsWith('.local')||h==='0.0.0.0'||h==='::1')return true;if(/^127\./.test(h)||/^10\./.test(h)||/^169\.254\./.test(h)||/^192\.168\./.test(h))return true;const m=h.match(/^172\.(\d{1,3})\./);return !!(m&&Number(m[1])>=16&&Number(m[1])<=31);}
function parsePublicUrl(raw){let u;try{u=new URL(String(raw||'').trim());}catch(_){throw new Error('올바른 http/https 주소가 아닙니다.');}if(!/^https?:$/.test(u.protocol))throw new Error('http/https 주소만 사용할 수 있습니다.');if(isPrivateHost(u.hostname))throw new Error('localhost·사설 네트워크 주소는 가져올 수 없습니다.');return u;}
async function fetchText(url,{timeout=18000}={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'text/plain,text/markdown,text/html;q=0.9,*/*;q=0.5'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const text=await r.text();if(!text.trim())throw new Error('빈 응답');return text;}finally{clearTimeout(timer);}}
async function readUrl(raw){const u=parsePublicUrl(raw),seq=++fetchSeq;const reader='https://r.jina.ai/'+u.href;const text=await fetchText(reader);if(seq!==fetchSeq)return null;const cleaned=String(text||'').trim();if(cleaned.length<80)throw new Error('가져온 본문이 너무 짧습니다.');return{url:u.href,text:cleaned.slice(0,MAX_SOURCE_CHARS),via:'reader'};}
function tokenize(text){return (String(text||'').normalize('NFKC').toLowerCase().match(/[가-힣]{2,}|[a-z][a-z0-9_-]{2,}|\d{2,}/g)||[]).filter(w=>!STOP.has(w));}
function keywords(text,limit=12){const freq=new Map();for(const w of tokenize(text)){if(/^\d+$/.test(w)&&w.length<4)continue;freq.set(w,(freq.get(w)||0)+1);}return [...freq.entries()].sort((a,b)=>b[1]-a[1]||b[0].length-a[0].length).slice(0,limit).map(([word,count])=>({word,count}));}
function queryPlan(question){const k=keywords(question,8).map(x=>x.word),lead=k[0]||question.trim().slice(0,30)||'핵심 주제',second=k[1]||'공식',third=k[2]||'최신';return [...new Set([question.trim(),`${lead} ${second} 공식 자료`,`${lead} ${third} 최신`,`${lead} 통계 원문`,`${lead} 반박 논란 팩트체크`].filter(Boolean))].slice(0,5);}
function openGoogle(q){if(!q)return;window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank','noopener,noreferrer');}
function hostOf(url){try{return new URL(url).hostname.replace(/^www\./,'');}catch(_){return'';}}
function titleFromText(text,url,label=''){if(label)return label.trim();const line=String(text||'').split(/\n+/).map(x=>x.replace(/^#+\s*/,'').trim()).find(x=>x.length>=5&&x.length<=140);return line||hostOf(url)||'직접 입력 출처';}
function extractDate(text){const s=String(text||'').slice(0,12000);const pats=[/(20\d{2})[.\-\/]\s?(0?[1-9]|1[0-2])[.\-\/]\s?([0-2]?\d|3[01])/,/(20\d{2})년\s?(0?[1-9]|1[0-2])월\s?([0-2]?\d|3[01])일/];for(const p of pats){const m=s.match(p);if(m){const y=+m[1],mo=+m[2],d=+m[3];return `${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}}return'';}
function sourceQuality(src){let score=45;const h=hostOf(src.url);if(/(^|\.)(go\.kr|gov|ac\.kr|edu)(\.|$)/i.test(h))score+=30;if(/official|공식|보도자료|press release/i.test(src.text.slice(0,6000)))score+=12;if(src.date)score+=8;if(src.url)score+=5;return Math.min(100,score);}
function sentenceSplit(text){return String(text||'').replace(/\r/g,' ').split(/(?<=[.!?。！？]|다\.|요\.)\s+|\n+/).map(x=>x.trim()).filter(x=>x.length>=22&&x.length<=260);}
function extractClaims(src){const keyset=new Set(keywords(src.text,14).map(x=>x.word));const scored=sentenceSplit(src.text).map((sentence,i)=>{const toks=tokenize(sentence),numbers=sentence.match(/(?:\d[\d,.]*\s?(?:%|원|명|건|개|년|월|일|배|회|km|kg|GB|MB)?)/g)||[];let score=(numbers.length?3:0)+toks.filter(t=>keyset.has(t)).length+(i<12?1:0);return{sentence,tokens:new Set(toks),numbers,score};}).filter(x=>x.score>=2).sort((a,b)=>b.score-a.score).slice(0,MAX_CLAIMS_PER_SOURCE);return scored;}
function jaccard(a,b){if(!a.size||!b.size)return 0;let inter=0;for(const x of a)if(b.has(x))inter++;return inter/(a.size+b.size-inter);}
function numericSignature(claim){return claim.numbers.map(x=>x.replace(/\s+/g,'')).join('|');}
function addSource({url='',text='',label='',via='manual'}){const clean=String(text||'').trim().slice(0,MAX_SOURCE_CHARS);if(clean.length<20)throw new Error('출처 원문이 너무 짧습니다.');const normalized=tokenize(clean).slice(0,4000).join(' ');for(const s of sources){const a=new Set(normalized.split(' ').filter(Boolean)),b=new Set(s.normalized.split(' ').filter(Boolean));if(jaccard(a,b)>.88)return{s,duplicate:true};}
const src={id:++sourceSeq,url,text:clean,label,title:titleFromText(clean,url,label),domain:hostOf(url)||'직접 입력',date:extractDate(clean),via,normalized,claims:[]};src.claims=extractClaims(src);src.quality=sourceQuality(src);sources.push(src);renderSources();syncButtons();return{src,duplicate:false};}
function removeSource(id){const i=sources.findIndex(x=>x.id===id);if(i>=0)sources.splice(i,1);currentReport=null;renderSources();renderEmptyAnalysis();syncButtons();}
function renderSources(){const root=$('#reachSources');setText('reachSourceCount',`${sources.length}개`);if(!root)return;if(!sources.length){root.innerHTML='<div class="empty">아직 수집된 출처가 없습니다.</div>';return;}root.innerHTML=sources.map((s,i)=>`<article class="reachSourceItem" data-source-id="${s.id}"><div class="reachSourceTop"><div><b>${i+1}. ${esc(s.title)}</b><span>${esc(s.domain)}${s.date?` · ${esc(s.date)}`:''} · 품질 ${s.quality}</span></div><button class="mini" type="button" data-remove-source="${s.id}">제거</button></div><div class="reachSourceMeta"><span>${s.text.length.toLocaleString()}자</span><span>주장 후보 ${s.claims.length}</span><span>${s.via==='reader'?'URL 수집':'직접 입력'}</span></div>${s.url?`<a class="reachSourceLink" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">원문 열기</a>`:''}</article>`).join('');root.querySelectorAll('[data-remove-source]').forEach(btn=>btn.addEventListener('click',()=>removeSource(Number(btn.dataset.removeSource))));}
function claimGroups(){const entries=[];for(const s of sources)for(const c of s.claims)entries.push({source:s,claim:c});const groups=[];for(const e of entries){let best=null,bestSim=0;for(const g of groups){const sim=jaccard(e.claim.tokens,g.tokens);if(sim>bestSim){bestSim=sim;best=g;}}if(best&&bestSim>=.38){best.items.push(e);for(const t of e.claim.tokens)best.tokens.add(t);}else groups.push({tokens:new Set(e.claim.tokens),items:[e]});}return groups.sort((a,b)=>b.items.length-a.items.length||b.items[0].claim.score-a.items[0].claim.score).slice(0,24);}
function detectConflicts(groups){const out=[];for(const g of groups){const bySource=new Map();for(const item of g.items){const sig=numericSignature(item.claim);if(sig)bySource.set(item.source.id,{sig,item});}const vals=[...bySource.values()];if(vals.length>=2&&new Set(vals.map(x=>x.sig)).size>1)out.push({topic:g.items[0].claim.sentence,items:vals.map(x=>x.item)});}return out.slice(0,12);}
function analyzeResearch(){if(!sources.length)return false;const groups=claimGroups(),conflicts=detectConflicts(groups),allText=sources.map(s=>s.text).join('\n'),keys=keywords(allText,12);const supported=groups.filter(g=>new Set(g.items.map(x=>x.source.domain)).size>=2||g.items.some(x=>x.source.quality>=80));currentReport={question:$('#reachQuestion')?.value.trim()||'',queries:queryPlan($('#reachQuestion')?.value||allText.slice(0,200)),sources:[...sources],groups,conflicts,keywords:keys,supported};renderReport(currentReport);return true;}
function renderReport(r){setText('reachResultStatus','교차검증 완료');setText('reachSourceMetric',String(r.sources.length));setText('reachClaimMetric',String(r.groups.length));setText('reachConflictMetric',String(r.conflicts.length));setText('reachPackStatus',`${r.supported.length}개 근거 후보`);
$('#reachKeywords').innerHTML=r.keywords.length?r.keywords.map(k=>`<span>${esc(k.word)} <small>×${k.count}</small></span>`).join(''):'<span class="sub">핵심어를 찾지 못했습니다.</span>';
$('#reachClaims').innerHTML=r.groups.length?r.groups.slice(0,12).map((g,i)=>{const domains=[...new Set(g.items.map(x=>x.source.domain))];return `<div class="reachClaimItem ${domains.length>=2?'supported':'single'}"><div><b>${i+1}. ${esc(g.items[0].claim.sentence)}</b><span>${domains.length}개 독립 도메인 · ${g.items.length}개 근거 문장</span></div><div class="reachClaimSources">${domains.map(d=>`<span>${esc(d)}</span>`).join('')}</div></div>`;}).join(''):'<div class="empty">주장 후보를 찾지 못했습니다.</div>';
$('#reachConflicts').innerHTML=r.conflicts.length?r.conflicts.map((c,i)=>`<div class="reachConflictItem"><b>상충 ${i+1}</b><span>${esc(c.topic)}</span><ul>${c.items.map(x=>`<li>${esc(x.source.domain)} · ${esc(x.claim.sentence)}</li>`).join('')}</ul></div>`).join(''):'<div class="reachNoConflict">뚜렷한 숫자·날짜 상충 신호를 찾지 못했습니다.</div>';
$('#reachQuality').innerHTML=r.sources.map(s=>`<div class="reachQualityItem"><b>${esc(s.domain)}</b><span>품질 ${s.quality}/100${s.date?` · 날짜 ${esc(s.date)}`:' · 날짜 미확인'} · ${s.claims.length}개 주장 후보</span></div>`).join('');
$('#reachEvidencePack').innerHTML=r.supported.length?r.supported.slice(0,12).map((g,i)=>{const ds=[...new Set(g.items.map(x=>x.source.domain))];const official=g.items.some(x=>x.source.quality>=80);return `<article class="reachEvidenceItem"><div class="reachEvidenceState ${ds.length>=2?'strong':official?'official':'weak'}">${ds.length>=2?'독립 출처 지지':official?'원출처 우선':'추가 확인'}</div><b>${i+1}. ${esc(g.items[0].claim.sentence)}</b><span>근거: ${ds.map(esc).join(', ')}</span></article>`;}).join(''):'<div class="empty">충분한 지지 근거를 찾지 못했습니다. 출처를 더 추가해 주세요.</div>';
const lead=r.keywords[0]?.word||r.question||'핵심 주제';$('#reachReuse').innerHTML=[['네이버 블로그',`${lead} 관련 근거팩에서 독립 출처 지지가 있는 항목을 본문 핵심으로 사용하고, 상충 항목은 단정하지 말고 별도 주의문으로 표시.`],['숏츠 / 릴스',`검증된 주장 1~2개만 30~60초로 압축하고 영상 설명에 원문 출처를 남김.`],['커뮤니티',`핵심 사실 3줄 + 출처 도메인 + 상충 여부를 함께 표시.`]].map(x=>`<div class="reachItem"><b>${x[0]}</b><small>${esc(x[1])}</small></div>`).join('');$('#reachHooks').innerHTML=[`${lead}, 여러 출처로 다시 확인해봤습니다`,`${lead} 정보에서 출처마다 달랐던 부분`,`${lead} 공식·독립 출처를 나눠서 보면`,`${lead} 관련 핵심 근거만 정리`].map((x,i)=>`<div class="reachItem"><b>${i+1}</b>${esc(x)}</div>`).join('');$('#reachCopyAll').disabled=false;$('#reachSaveTxt').disabled=false;showToast('GomFox Reach 교차검증 완료');}
function reportText(r=currentReport){if(!r)return'';const lines=['GomFox Reach 3.0 Research Evidence Pack',r.question?`조사 질문: ${r.question}`:'',`출처: ${r.sources.length}개 · 주장 그룹: ${r.groups.length}개 · 상충: ${r.conflicts.length}개`,'','[검색어]',...r.queries.map((q,i)=>`${i+1}. ${q}`),'','[출처]',...r.sources.map((s,i)=>`${i+1}. ${s.title} | ${s.url||s.domain} | 품질 ${s.quality}${s.date?` | ${s.date}`:''}`),'','[지지 근거]',...r.supported.map((g,i)=>`${i+1}. ${g.items[0].claim.sentence}\n   근거: ${[...new Set(g.items.map(x=>x.source.domain))].join(', ')}`),'','[상충 신호]',...(r.conflicts.length?r.conflicts.map((c,i)=>`${i+1}. ${c.topic}\n${c.items.map(x=>`   - ${x.source.domain}: ${x.claim.sentence}`).join('\n')}`):['없음'])];return lines.filter(x=>x!==undefined&&x!=='').join('\n');}
async function copy(text,label='복사'){if(!text)return false;try{await navigator.clipboard.writeText(text);showToast(`${label} 완료`);return true;}catch(_){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();showToast(ok?`${label} 완료`:'복사하지 못했습니다. 직접 선택해 주세요.');return ok;}}
function saveTxt(){const text=reportText();if(!text)return;const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`GomFox-Reach-Evidence-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);}
function renderPlan(){const q=$('#reachQuestion').value.trim();if(!q){setStatus('reachPlanStatus','조사 질문을 입력해 주세요.','warn');return false;}const plan=queryPlan(q);$('#reachQueries').innerHTML=plan.map((x,i)=>`<div class="reachQueryItem"><button type="button" data-open-query="${i}" aria-label="Google에서 검색">↗</button><span>${esc(x)}</span></div>`).join('');$('#reachQueries').querySelectorAll('[data-open-query]').forEach((btn,i)=>btn.addEventListener('click',()=>openGoogle(plan[i])));$('#reachOpenSearch').disabled=false;$('#reachOpenSearchAll').disabled=false;$('#reachOpenSearch').dataset.query=plan[0]||q;$('#reachOpenSearchAll').dataset.queries=JSON.stringify(plan);setStatus('reachPlanStatus',`${plan.length}개 검색어 준비 · 검색 결과에서 신뢰할 출처 URL을 복사해 다음 단계에 넣으세요.`,'ok');return true;}
async function fetchMany(){const raw=$('#reachUrls').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const unique=[...new Set(raw)].slice(0,MAX_SOURCES);if(!unique.length){setStatus('reachFetchStatus','수집할 URL을 한 줄에 하나씩 넣어 주세요.','warn');return;}const room=Math.max(0,MAX_SOURCES-sources.length);if(!room){setStatus('reachFetchStatus',`출처는 최대 ${MAX_SOURCES}개입니다. 기존 출처를 제거해 주세요.`,'warn');return;}const targets=unique.slice(0,room);const btn=$('#reachFetchMany');btn.disabled=true;let ok=0,dup=0,fail=0;for(let i=0;i<targets.length;i++){setStatus('reachFetchStatus',`${i+1}/${targets.length} 수집 중 · ${targets[i]}`);try{const r=await readUrl(targets[i]);if(!r)continue;const added=addSource({url:r.url,text:r.text,via:'reader'});added.duplicate?dup++:ok++;}catch(_){fail++;}}btn.disabled=false;setStatus('reachFetchStatus',`수집 완료 · 추가 ${ok} · 중복 ${dup} · 실패 ${fail}`,fail?'warn':'ok');if(ok)showToast(`${ok}개 출처 수집 완료`);}
function addManual(){try{const r=addSource({text:$('#reachRaw').value,label:$('#reachManualLabel').value,via:'manual'});setStatus('reachFetchStatus',r.duplicate?'이미 비슷한 출처가 있어 중복으로 제외했습니다.':'직접 붙여넣기 출처를 추가했습니다.',r.duplicate?'warn':'ok');if(!r.duplicate){$('#reachRaw').value='';$('#reachManualLabel').value='';}}catch(err){setStatus('reachFetchStatus',err.message||String(err),'warn');}}
function renderEmptyAnalysis(){setText('reachResultStatus','분석 대기');setText('reachSourceMetric',String(sources.length));setText('reachClaimMetric','0');setText('reachConflictMetric','0');setText('reachPackStatus','근거 대기');$('#reachKeywords').innerHTML='<span class="sub">출처를 분석하면 표시됩니다.</span>';$('#reachClaims').innerHTML='<span class="sub">여러 출처에서 반복되는 주장과 근거를 찾습니다.</span>';$('#reachConflicts').innerHTML='<span class="sub">숫자·날짜·핵심 표현이 충돌하는 경우 표시합니다.</span>';$('#reachQuality').innerHTML='<span class="sub">원출처 가능성·날짜·독립 출처 여부를 점검합니다.</span>';$('#reachEvidencePack').innerHTML='<div class="empty">교차검증을 실행하면 근거팩이 생성됩니다.</div>';$('#reachReuse').innerHTML='<span class="sub">검증 결과를 바탕으로 블로그·숏폼용 작업 가이드를 만듭니다.</span>';$('#reachHooks').innerHTML='<span class="sub">조사 질문과 검증된 핵심어를 바탕으로 후보를 만듭니다.</span>';$('#reachCopyAll').disabled=true;$('#reachSaveTxt').disabled=true;}
function syncButtons(){$('#reachAnalyze').disabled=!sources.length;setText('reachSourceMetric',String(sources.length));}
function clearAll(){fetchSeq++;sources.splice(0);currentReport=null;for(const id of ['reachQuestion','reachUrls','reachManualLabel','reachRaw']){const el=$('#'+id);if(el)el.value='';}$('#reachQueries').innerHTML='<span class="sub">질문을 분석하면 검색어가 표시됩니다.</span>';$('#reachOpenSearch').disabled=true;$('#reachOpenSearchAll').disabled=true;setStatus('reachPlanStatus','질문을 입력하면 핵심어와 확인용 검색어를 만듭니다.');setStatus('reachFetchStatus','공개 URL은 읽기 전용 Reader를 통해 가져옵니다. 로그인·캡차가 필요한 글은 아래에 직접 붙여넣으세요.');renderSources();renderEmptyAnalysis();syncButtons();}
function init(opts={}){if(opts.showToast)showToast=opts.showToast;if(initialized)return api;const required=['reachQuestion','reachPlan','reachQueries','reachUrls','reachFetchMany','reachRaw','reachAddCurrent','reachSources','reachAnalyze','reachClaims','reachConflicts','reachQuality','reachEvidencePack','reachCopyAll','reachSaveTxt'];const missing=required.filter(id=>!document.getElementById(id));if(missing.length)throw new Error('Reach UI 누락: '+missing.join(', '));initialized=true;setText('reachEngineBadge','Research Engine 연결 완료');$('#reachPlan').addEventListener('click',renderPlan);$('#reachOpenSearch').addEventListener('click',()=>openGoogle($('#reachOpenSearch').dataset.query||$('#reachQuestion').value));$('#reachOpenSearchAll').addEventListener('click',()=>{let qs=[];try{qs=JSON.parse($('#reachOpenSearchAll').dataset.queries||'[]');}catch(_){}qs.slice(0,5).forEach((q,i)=>setTimeout(()=>openGoogle(q),i*120));});$('#reachFetchMany').addEventListener('click',fetchMany);$('#reachAddCurrent').addEventListener('click',addManual);$('#reachCopySource').addEventListener('click',()=>copy($('#reachRaw').value,'원문 복사'));$('#reachAnalyze').addEventListener('click',analyzeResearch);$('#reachCopyAll').addEventListener('click',()=>copy(reportText(),'근거팩 복사'));$('#reachSaveTxt').addEventListener('click',saveTxt);$('#reachClear').addEventListener('click',clearAll);renderSources();renderEmptyAnalysis();syncButtons();return api;}
function activate(){active=true;}
function deactivate(){active=false;fetchSeq++;const btn=$('#reachFetchMany');if(btn)btn.disabled=false;}
const api={init,activate,deactivate,readUrl,addSource,analyzeResearch,queryPlan,get sources(){return [...sources];},get active(){return active;}};window.GomFoxReach=api;
})();
